namespace BeautyByNegin.Web.Areas.Admin;

// Panel texts: P(key, فارسی, Türkçe, Deutsch, English). Plain words, no technical terms.
public static partial class PanelText
{
    private static IEnumerable<Entry> Entries() =>
    [
        // ---------------------------------------------------------------- general
        P("panel.name", "پنل مدیریت", "Yönetim Paneli", "Verwaltung", "Admin Panel"),
        P("toast.saved", "✅ ذخیره شد", "✅ Kaydedildi", "✅ Gespeichert", "✅ Saved"),
        P("toast.error", "مشکلی پیش آمد. دوباره امتحان کنید.", "Bir sorun oluştu. Lütfen tekrar deneyin.", "Etwas ist schiefgelaufen. Bitte erneut versuchen.", "Something went wrong. Please try again."),
        P("toast.movedToTrash", "به سطل زباله منتقل شد (تا ۳۰ روز قابل برگرداندن است)", "Çöp kutusuna taşındı (30 gün içinde geri alınabilir)", "In den Papierkorb verschoben (30 Tage wiederherstellbar)", "Moved to the Trash (can be restored for 30 days)"),
        P("toast.deleted", "حذف شد", "Silindi", "Gelöscht", "Deleted"),
        P("toast.duplicated", "یک نسخه‌ی کپی ساخته شد (فعلاً در سایت نمایش داده نمی‌شود)", "Bir kopya oluşturuldu (şimdilik sitede gizli)", "Eine Kopie wurde erstellt (vorerst auf der Website ausgeblendet)", "A copy was created (hidden on the site for now)"),

        P("common.save", "ذخیره", "Kaydet", "Speichern", "Save"),
        P("common.cancel", "انصراف", "Vazgeç", "Abbrechen", "Cancel"),
        P("common.add", "افزودن", "Ekle", "Hinzufügen", "Add"),
        P("common.addNew", "مورد جدید", "Yeni ekle", "Neuer Eintrag", "Add new"),
        P("common.edit", "ویرایش", "Düzenle", "Bearbeiten", "Edit"),
        P("common.delete", "حذف", "Sil", "Löschen", "Delete"),
        P("common.duplicate", "کپی کردن", "Kopyala", "Duplizieren", "Duplicate"),
        P("common.open", "باز کردن", "Aç", "Öffnen", "Open"),
        P("common.all", "همه", "Tümü", "Alle", "All"),
        P("common.search", "جستجو", "Ara", "Suchen", "Search"),
        P("common.filter", "نمایش", "Filtrele", "Filtern", "Filter"),
        P("common.from", "از تاریخ", "Başlangıç", "Von", "From"),
        P("common.to", "تا تاریخ", "Bitiş", "Bis", "To"),
        P("common.test", "امتحان کن", "Dene", "Testen", "Test"),
        P("common.viewAll", "همه را ببین", "Tümünü gör", "Alle ansehen", "View all"),
        P("common.backToList", "بازگشت به فهرست", "Listeye dön", "Zurück zur Liste", "Back to list"),
        P("common.viewOnSite", "دیدن در سایت", "Sitede gör", "Auf der Website ansehen", "View on site"),
        P("common.visible", "نمایش", "Görünür", "Sichtbar", "Visible"),
        P("common.visibleHelp", "خاموش کنید تا بدون حذف کردن، از سایت پنهان شود", "Silmeden siteden gizlemek için kapatın", "Ausschalten, um es ohne Löschen auf der Website auszublenden", "Switch off to hide it on the site without deleting"),
        P("common.showOnSite", "در سایت نمایش داده شود", "Sitede göster", "Auf der Website anzeigen", "Show on the site"),
        P("common.drag", "برای جابه‌جایی بکشید", "Taşımak için sürükleyin", "Zum Verschieben ziehen", "Drag to move"),
        P("common.dragHelp", "برای تغییر ترتیب، ردیف‌ها را با نگه داشتن ⠿ بکشید (در موبایل از فلش‌ها استفاده کنید). ترتیب خودکار ذخیره می‌شود.", "Sırayı değiştirmek için satırları ⠿ ile sürükleyin (telefonda okları kullanın). Sıra otomatik kaydedilir.", "Zum Umsortieren die Zeilen an ⠿ ziehen (am Handy die Pfeile nutzen). Die Reihenfolge wird automatisch gespeichert.", "Drag rows by ⠿ to change the order (use the arrows on a phone). The order is saved automatically."),
        P("common.moveUp", "بالا", "Yukarı", "Nach oben", "Move up"),
        P("common.moveDown", "پایین", "Aşağı", "Nach unten", "Move down"),
        P("common.advanced", "تنظیمات پیشرفته ▾", "Gelişmiş ayarlar ▾", "Erweiterte Einstellungen ▾", "Advanced settings ▾"),
        P("common.slug", "آدرس صفحه", "Sayfa adresi", "Seitenadresse", "Page address"),
        P("common.slugHelp", "قسمت آخر آدرس صفحه در مرورگر. اگر خالی بماند، خودکار از روی نام ساخته می‌شود. بهتر است بعد از انتشار تغییرش ندهید (آدرس قدیمی خودکار به جدید منتقل می‌شود).", "Tarayıcıdaki adresin son kısmı. Boş bırakılırsa addan otomatik oluşturulur. Yayından sonra değiştirmemeniz önerilir (eski adres yeniye yönlendirilir).", "Letzter Teil der Adresse im Browser. Leer lassen = automatisch aus dem Namen. Nach Veröffentlichung besser nicht ändern (die alte Adresse leitet automatisch weiter).", "The last part of the address in the browser. Left empty, it is made from the name. Better not to change it after publishing (the old address redirects automatically)."),
        P("common.metaTitle", "عنوانی که در گوگل دیده می‌شود", "Google'da görünen başlık", "Titel in Google", "Title shown on Google"),
        P("common.metaTitleHelp", "اگر خالی بماند، نام همین صفحه استفاده می‌شود.", "Boş bırakılırsa sayfanın adı kullanılır.", "Leer lassen = Name der Seite wird verwendet.", "If empty, the page name is used."),
        P("common.metaDescription", "توضیحی که در گوگل دیده می‌شود", "Google'da görünen açıklama", "Beschreibung in Google", "Description shown on Google"),
        P("common.metaDescriptionHelp", "یک یا دو جمله. اگر خالی بماند، از متن کوتاه استفاده می‌شود.", "Bir iki cümle. Boş bırakılırsa kısa açıklama kullanılır.", "Ein bis zwei Sätze. Leer lassen = Kurztext wird verwendet.", "One or two sentences. If empty, the short text is used."),
        P("common.confirmTrash", "این مورد به سطل زباله منتقل شود؟ تا ۳۰ روز می‌توانید آن را برگردانید.", "Bu öğe çöp kutusuna taşınsın mı? 30 gün içinde geri alabilirsiniz.", "In den Papierkorb verschieben? Sie können es 30 Tage lang wiederherstellen.", "Move this to the Trash? You can restore it for 30 days."),
        P("common.confirmDelete", "مطمئن هستید؟ این کار قابل برگشت نیست.", "Emin misiniz? Bu işlem geri alınamaz.", "Sind Sie sicher? Das kann nicht rückgängig gemacht werden.", "Are you sure? This cannot be undone."),
        P("common.yesDelete", "بله", "Evet", "Ja", "Yes"),
        P("common.unsavedWarning", "تغییرات ذخیره نشده‌اند. واقعاً می‌خواهید از این صفحه خارج شوید؟", "Kaydedilmemiş değişiklikler var. Sayfadan çıkmak istiyor musunuz?", "Es gibt ungespeicherte Änderungen. Seite wirklich verlassen?", "You have unsaved changes. Leave this page anyway?"),

        P("tabs.missing", "این زبان هنوز نوشته نشده", "Bu dil eksik", "Diese Sprache fehlt noch", "This language is missing"),
        P("tabs.missingNote", "این زبان هنوز نوشته نشده است. تا وقتی خالی باشد، در سایت متن زبان اصلی نشان داده می‌شود.", "Bu dil eksik. Boş kaldığı sürece sitede ana dildeki metin gösterilir.", "Diese Sprache fehlt noch. Solange sie leer ist, zeigt die Website den Text der Hauptsprache.", "This language is missing. While empty, the site shows the text of the main language."),
        P("tabs.textMissing", "این متن در این زبان خالی است.", "Bu metin bu dilde boş.", "Dieser Text ist in dieser Sprache leer.", "This text is empty in this language."),

        P("image.choose", "انتخاب عکس", "Fotoğraf seç", "Foto auswählen", "Choose photo"),
        P("image.addMany", "افزودن عکس (چند تا با هم)", "Fotoğraf ekle (birden çok)", "Fotos hinzufügen (mehrere)", "Add photos (several)"),
        P("image.remove", "برداشتن عکس", "Fotoğrafı kaldır", "Foto entfernen", "Remove photo"),
        P("image.none", "هنوز عکسی انتخاب نشده (می‌توانید عکس را اینجا بکشید)", "Henüz fotoğraf yok (buraya sürükleyebilirsiniz)", "Noch kein Foto (Sie können es hierher ziehen)", "No photo yet (you can drag one here)"),
        P("media.empty", "فایلی انتخاب نشده است.", "Dosya seçilmedi.", "Keine Datei ausgewählt.", "No file selected."),
        P("media.tooLarge", "این عکس خیلی بزرگ است (بیشتر از ۲۰ مگابایت). لطفاً عکس کوچک‌تری انتخاب کنید.", "Bu fotoğraf çok büyük (20 MB üzeri). Lütfen daha küçük bir fotoğraf seçin.", "Dieses Foto ist zu groß (über 20 MB). Bitte ein kleineres wählen.", "This photo is too large (over 20 MB). Please choose a smaller one."),
        P("media.notImage", "این فایل عکس نیست یا قابل خواندن نیست. لطفاً یک عکس JPG، PNG یا WebP انتخاب کنید.", "Bu dosya bir fotoğraf değil. Lütfen JPG, PNG veya WebP seçin.", "Diese Datei ist kein lesbares Foto. Bitte JPG, PNG oder WebP wählen.", "This file is not a readable photo. Please choose a JPG, PNG or WebP."),

        P("err.required", "این قسمت لازم است.", "Bu alan zorunlu.", "Dieses Feld ist erforderlich.", "This field is required."),
        P("err.nameRequired", "نام لازم است (حداقل در زبان اصلی).", "Ad zorunlu (en azından ana dilde).", "Name ist erforderlich (mindestens in der Hauptsprache).", "A name is required (at least in the main language)."),
        P("err.titleRequired", "عنوان لازم است (حداقل در زبان اصلی).", "Başlık zorunlu (en azından ana dilde).", "Titel ist erforderlich (mindestens in der Hauptsprache).", "A title is required (at least in the main language)."),
        P("err.textRequired", "متن لازم است.", "Metin zorunlu.", "Text ist erforderlich.", "Text is required."),
        P("err.slugTaken", "این آدرس صفحه قبلاً استفاده شده است. یک آدرس دیگر بنویسید.", "Bu sayfa adresi zaten kullanılıyor. Başka bir adres yazın.", "Diese Seitenadresse ist schon vergeben. Bitte eine andere wählen.", "This page address is already used. Please choose another."),
        P("err.notFound", "پیدا نشد.", "Bulunamadı.", "Nicht gefunden.", "Not found."),
        P("err.emailInvalid", "آدرس ایمیل درست نیست.", "E-posta adresi geçersiz.", "Die E-Mail-Adresse ist ungültig.", "The email address is not valid."),
        P("err.defaultMustBeEnabled", "زبان اصلی باید روشن باشد.", "Varsayılan dil açık olmalı.", "Die Hauptsprache muss aktiv sein.", "The main language must be switched on."),

        // ---------------------------------------------------------------- menu
        P("nav.dashboard", "خانه‌ی پنل", "Kontrol Paneli", "Übersicht", "Dashboard"),
        P("nav.appointments", "درخواست‌های نوبت", "Randevu Talepleri", "Terminanfragen", "Appointment Requests"),
        P("nav.appointmentsShort", "نوبت‌ها", "Randevular", "Termine", "Bookings"),
        P("nav.messages", "پیام‌ها", "Mesajlar", "Nachrichten", "Messages"),
        P("nav.chats", "چت‌ها", "Sohbetler", "Chats", "Chats"),
        P("nav.services", "خدمات", "Hizmetler", "Behandlungen", "Services"),
        P("nav.gallery", "گالری", "Galeri", "Galerie", "Gallery"),
        P("nav.reviews", "نظرات", "Yorumlar", "Bewertungen", "Reviews"),
        P("nav.home", "صفحه‌ی اصلی", "Ana Sayfa", "Startseite", "Home Page"),
        P("nav.about", "درباره‌ی ما", "Hakkımızda", "Über uns", "About"),
        P("nav.contact", "اطلاعات تماس و شبکه‌های اجتماعی", "İletişim & Sosyal Medya", "Kontakt & Social Media", "Contact & Social Media"),
        P("nav.pages", "صفحه‌ها", "Sayfalar", "Seiten", "Pages"),
        P("nav.newsletter", "خبرنامه", "Bülten", "Newsletter", "Newsletter"),
        P("nav.texts", "متن‌های سایت", "Site Metinleri", "Website-Texte", "Site Texts"),
        P("nav.languages", "زبان‌ها", "Diller", "Sprachen", "Languages"),
        P("nav.settings", "تنظیمات کلی", "Genel Ayarlar", "Einstellungen", "Settings"),
        P("nav.backup", "پشتیبان‌گیری", "Yedekleme", "Datensicherung", "Backup"),
        P("nav.trash", "سطل زباله", "Çöp Kutusu", "Papierkorb", "Trash"),
        P("nav.users", "کاربران پنل", "Panel Kullanıcıları", "Benutzer", "Users"),
        P("nav.help", "راهنما", "Yardım", "Hilfe", "Help"),
        P("nav.account", "حساب من", "Hesabım", "Mein Konto", "My Account"),
        P("nav.viewSite", "دیدن سایت", "Siteyi gör", "Website ansehen", "View website"),
        P("nav.logout", "خروج", "Çıkış", "Abmelden", "Log out"),
        P("nav.menu", "منو", "Menü", "Menü", "Menu"),
        P("nav.more", "بیشتر", "Daha fazla", "Mehr", "More"),

        // ---------------------------------------------------------------- dashboard
        P("dash.last7", "درخواست نوبت در ۷ روز گذشته", "son 7 günde randevu talebi", "Terminanfragen in den letzten 7 Tagen", "appointment requests in the last 7 days"),
        P("dash.newRequests", "درخواست جدید که هنوز پیگیری نشده", "henüz ilgilenilmemiş yeni talep", "neue, noch offene Anfragen", "new requests not handled yet"),
        P("dash.subscribers", "عضو خبرنامه", "bülten abonesi", "Newsletter-Abonnenten", "newsletter subscribers"),
        P("dash.latest", "آخرین درخواست‌های نوبت", "Son randevu talepleri", "Neueste Terminanfragen", "Latest appointment requests"),
        P("tile.dashboard", "", "", "", ""),
        P("tile.appointments", "درخواست‌هایی که از فرم رزرو سایت آمده‌اند", "Sitedeki randevu formundan gelen talepler", "Anfragen aus dem Buchungsformular", "Requests from the booking form"),
        P("tile.messages", "پیام‌های فرم تماس", "İletişim formundan gelen mesajlar", "Nachrichten aus dem Kontaktformular", "Messages from the contact form"),
        P("tile.chats", "گفتگوهای دکمه‌ی چت سایت", "Sitedeki sohbet butonundan konuşmalar", "Gespräche aus dem Chat der Website", "Conversations from the site chat"),
        P("tile.services", "افزودن، تغییر یا پنهان کردن خدمات", "Hizmet ekle, değiştir veya gizle", "Behandlungen hinzufügen, ändern, ausblenden", "Add, change or hide services"),
        P("tile.gallery", "عکس‌های گالری و قبل/بعد", "Galeri ve önce/sonra fotoğrafları", "Galeriefotos und Vorher/Nachher", "Gallery photos and before/after"),
        P("tile.reviews", "نظرات مشتریان", "Müşteri yorumları", "Kundenbewertungen", "Client reviews"),
        P("tile.home", "عکس بزرگ، شعار و بخش‌های صفحه‌ی اصلی", "Büyük fotoğraf, slogan ve bölümler", "Großes Foto, Slogan und Bereiche", "Big photo, slogan and sections"),
        P("tile.about", "عکس و معرفی شما", "Fotoğrafınız ve tanıtımınız", "Ihr Foto und Ihre Vorstellung", "Your photo and introduction"),
        P("tile.contact", "تلفن، واتس‌اپ، آدرس، ساعات کاری", "Telefon, WhatsApp, adres, saatler", "Telefon, WhatsApp, Adresse, Zeiten", "Phone, WhatsApp, address, hours"),
        P("tile.pages", "Impressum، حریم خصوصی و صفحه‌های دیگر", "Künye, gizlilik ve diğer sayfalar", "Impressum, Datenschutz und weitere Seiten", "Legal notice, privacy and other pages"),
        P("tile.texts", "متن دکمه‌ها، منو و فرم‌ها", "Buton, menü ve form metinleri", "Texte von Buttons, Menü, Formularen", "Button, menu and form texts"),
        P("tile.newsletter", "ایمیل‌های عضو شده در خبرنامه", "Bültene kayıtlı e-postalar", "Angemeldete E-Mail-Adressen", "Subscribed email addresses"),
        P("tile.languages", "روشن/خاموش کردن زبان‌ها", "Dilleri aç/kapat", "Sprachen ein-/ausschalten", "Switch languages on/off"),
        P("tile.settings", "لوگو، کشور، ایمیل، تلگرام", "Logo, ülke, e-posta, Telegram", "Logo, Land, E-Mail, Telegram", "Logo, country, email, Telegram"),
        P("tile.backup", "دانلود یا برگرداندن نسخه‌ی پشتیبان", "Yedeği indir veya geri yükle", "Sicherung herunterladen/wiederherstellen", "Download or restore a backup"),
        P("tile.trash", "برگرداندن موارد حذف‌شده", "Silinenleri geri al", "Gelöschtes wiederherstellen", "Restore deleted items"),
        P("tile.account", "تغییر رمز عبور و زبان پنل", "Şifre ve panel dili", "Passwort und Sprache", "Password and panel language"),
        P("tile.help", "راهنمای ساده‌ی پنل", "Basit kullanım kılavuzu", "Einfache Anleitung", "Simple user guide"),
        P("tile.users", "", "", "", ""),

        // ---------------------------------------------------------------- intros (1–2 sentences on top of each screen)
        P("intro.account", "در این بخش می‌توانید رمز عبور خود را عوض کنید. زبان پنل را از بالای صفحه انتخاب کنید.", "Burada şifrenizi değiştirebilirsiniz. Panel dilini sayfanın üstünden seçin.", "Hier ändern Sie Ihr Passwort. Die Sprache der Verwaltung wählen Sie oben.", "Change your password here. Choose the panel language at the top."),
        P("intro.appointments", "درخواست‌هایی که مشتریان در فرم «رزرو نوبت» سایت فرستاده‌اند. با یک لمس تماس بگیرید یا در واتس‌اپ پیام بدهید و وضعیت را به‌روز کنید.", "Müşterilerin sitedeki randevu formundan gönderdiği talepler. Tek dokunuşla arayın veya WhatsApp'tan yazın, durumu güncelleyin.", "Anfragen aus dem Buchungsformular der Website. Mit einem Tipp anrufen oder per WhatsApp schreiben und den Status aktualisieren.", "Requests sent through the booking form. Call or WhatsApp with one tap and update the status."),
        P("intro.messages", "پیام‌هایی که از فرم کوتاه صفحه‌ی «تماس» آمده‌اند.", "İletişim sayfasındaki kısa formdan gelen mesajlar.", "Nachrichten aus dem kurzen Formular der Kontaktseite.", "Messages from the short form on the contact page."),
        P("intro.chats", "گفتگوهای دکمه‌ی چت (پایین سمت چپ سایت). جواب شما در همان پنجره‌ی چت برای مشتری نمایش داده می‌شود.", "Sohbet butonundan (sitenin sol alt köşesi) gelen konuşmalar. Cevabınız müşterinin sohbet penceresinde görünür.", "Gespräche aus dem Chat (unten links auf der Website). Ihre Antwort erscheint im Chatfenster der Kundin.", "Conversations from the chat button (bottom left of the site). Your reply appears in the visitor's chat window."),
        P("intro.newsletter", "کسانی که در صفحه‌ی اصلی در خبرنامه عضو شده‌اند. می‌توانید فهرست را برای اکسل دانلود کنید.", "Ana sayfada bültene kaydolanlar. Listeyi Excel için indirebilirsiniz.", "Personen, die sich auf der Startseite angemeldet haben. Die Liste lässt sich für Excel herunterladen.", "People who subscribed on the home page. You can download the list for Excel."),
        P("intro.services", "در این بخش می‌توانید خدمات سایت را اضافه، ویرایش یا پنهان کنید و ترتیب نمایش آن‌ها را عوض کنید.", "Bu bölümde sitedeki hizmetleri ekleyebilir, değiştirebilir veya gizleyebilir, sıralarını değiştirebilirsiniz.", "Hier können Sie Behandlungen hinzufügen, ändern, ausblenden und ihre Reihenfolge ändern.", "Here you can add, change or hide services and change their order."),
        P("intro.serviceEdit", "متن‌های این خدمت را برای هر زبان در تب خودش بنویسید. نام خدمت معمولاً در همه‌ی زبان‌ها انگلیسی می‌ماند.", "Bu hizmetin metinlerini her dil için kendi sekmesine yazın. Hizmet adı genelde tüm dillerde İngilizce kalır.", "Schreiben Sie die Texte jeder Sprache in ihren Tab. Der Name bleibt meist in allen Sprachen Englisch.", "Write the texts for each language in its own tab. The service name usually stays English in all languages."),
        P("intro.gallery", "عکس‌های صفحه‌ی گالری. می‌توانید چند عکس را با هم آپلود کنید؛ عکس‌ها خودکار کوچک و سبک می‌شوند.", "Galeri sayfasının fotoğrafları. Birden çok fotoğrafı aynı anda yükleyebilirsiniz; otomatik olarak küçültülür.", "Fotos der Galerieseite. Sie können mehrere auf einmal hochladen; sie werden automatisch verkleinert.", "Photos of the gallery page. Upload several at once; they are resized automatically."),
        P("intro.galleryEdit", "عکس، دسته و توضیح این عکس را تغییر دهید. اگر عکس «بعد» اضافه کنید، در سایت به شکل مقایسه‌ی قبل/بعد نمایش داده می‌شود.", "Fotoğrafı, kategoriyi ve açıklamayı değiştirin. Bir \"sonra\" fotoğrafı eklerseniz sitede önce/sonra olarak gösterilir.", "Foto, Kategorie und Beschreibung ändern. Mit einem „Nachher“-Foto erscheint es als Vorher/Nachher-Vergleich.", "Change the photo, category and caption. Adding an \"after\" photo shows it as a before/after comparison."),
        P("intro.galleryCategories", "دسته‌های گالری (دکمه‌های فیلتر بالای گالری). نام هر دسته را در هر زبان بنویسید.", "Galeri kategorileri (galerinin üstündeki filtreler). Her dil için adı yazın.", "Galerie-Kategorien (Filter über der Galerie). Den Namen für jede Sprache eintragen.", "Gallery categories (filters above the gallery). Write the name for each language."),
        P("intro.reviews", "نظرات مشتریان. نظرهایی که خودتان اضافه می‌کنید فوراً منتشر می‌شوند؛ نظرهای بازدیدکنندگان اول باید تأیید شوند.", "Müşteri yorumları. Sizin eklediğiniz yorumlar hemen yayınlanır; ziyaretçi yorumları önce onay bekler.", "Kundenbewertungen. Selbst eingetragene erscheinen sofort; Bewertungen von Besuchern müssen zuerst freigegeben werden.", "Client reviews. Reviews you add are published at once; visitor reviews wait for approval."),
        P("intro.home", "عکس بزرگ بالای صفحه‌ی اصلی، شعار و متن‌ها. بخش‌های صفحه‌ی اصلی را هم می‌توانید روشن/خاموش کنید و ترتیبشان را عوض کنید.", "Ana sayfanın büyük fotoğrafı, slogan ve metinler. Bölümleri açıp kapatabilir ve sıralarını değiştirebilirsiniz.", "Großes Foto, Slogan und Texte der Startseite. Bereiche lassen sich ein-/ausschalten und umsortieren.", "The big home page photo, slogan and texts. You can also switch sections on/off and reorder them."),
        P("intro.about", "عکس و معرفی شما در صفحه‌ی «درباره‌ی ما»، فهرست تخصص‌ها و مدارک.", "\"Hakkımızda\" sayfasındaki fotoğrafınız, tanıtımınız, uzmanlıklar ve sertifikalar.", "Ihr Foto und Ihre Vorstellung auf „Über uns“, Schwerpunkte und Zertifikate.", "Your photo and introduction on the About page, specialties and certificates."),
        P("intro.contact", "شماره‌ی تلفن، واتس‌اپ، ایمیل، اینستاگرام، آدرس و ساعات کاری. این اطلاعات در همه‌ی دکمه‌های تماس سایت استفاده می‌شوند.", "Telefon, WhatsApp, e-posta, Instagram, adres ve çalışma saatleri. Sitedeki tüm iletişim butonları bunları kullanır.", "Telefon, WhatsApp, E-Mail, Instagram, Adresse und Öffnungszeiten. Alle Kontakt-Buttons der Website verwenden diese Angaben.", "Phone, WhatsApp, email, Instagram, address and opening hours. All contact buttons on the site use these."),
        P("intro.pages", "صفحه‌های متنی مثل Impressum و حریم خصوصی، و صفحه‌های دلخواه (مثلاً «توصیه‌های بعد از درمان»).", "Künye ve gizlilik gibi metin sayfaları ile özel sayfalar (ör. \"Bakım sonrası öneriler\").", "Textseiten wie Impressum und Datenschutz sowie eigene Seiten (z. B. „Pflegetipps nach der Behandlung“).", "Text pages like the legal notice and privacy policy, and your own pages (e.g. \"Aftercare tips\")."),
        P("intro.pageEdit", "عنوان و متن صفحه را برای هر زبان بنویسید.", "Sayfanın başlığını ve metnini her dil için yazın.", "Titel und Text der Seite für jede Sprache schreiben.", "Write the page title and text for each language."),
        P("intro.texts", "متن دکمه‌ها، منو، فرم‌ها و پیام‌های سایت. یک گروه را باز کنید یا جستجو کنید.", "Butonlar, menü, formlar ve mesajların metinleri. Bir grup açın veya arayın.", "Texte von Buttons, Menü, Formularen und Meldungen. Eine Gruppe öffnen oder suchen.", "Texts of buttons, menu, forms and messages. Open a group or search."),
        P("intro.languages", "زبان‌های سایت را روشن/خاموش کنید و زبان اصلی را انتخاب کنید. مثلاً بعد از رفتن به آلمان، آلمانی را زبان اصلی کنید.", "Site dillerini açıp kapatın ve varsayılan dili seçin. Örneğin Almanya'ya taşınınca Almancayı varsayılan yapın.", "Sprachen ein-/ausschalten und die Hauptsprache wählen – z. B. nach dem Umzug nach Deutschland Deutsch.", "Switch site languages on/off and choose the main language – e.g. German after moving to Germany."),
        P("intro.settings", "تنظیمات کلی سایت: نام و لوگو، کشور و ساعت، ایمیل، تلگرام و بخش‌هایی که روشن یا خاموش‌اند.", "Genel ayarlar: ad ve logo, ülke ve saat, e-posta, Telegram ve açık/kapalı özellikler.", "Allgemeine Einstellungen: Name und Logo, Land und Zeit, E-Mail, Telegram und Funktionen.", "General settings: name and logo, country and time, email, Telegram and features."),
        P("intro.backup", "با یک کلیک از همه‌چیز (اطلاعات و عکس‌ها) یک فایل zip بگیرید. برای انتقال سایت به سرور جدید هم از همین فایل استفاده می‌شود.", "Tek tıkla her şeyin (veriler ve fotoğraflar) zip dosyasını alın. Siteyi yeni sunucuya taşımak için de bu dosya kullanılır.", "Mit einem Klick alles (Daten und Fotos) als ZIP sichern. Mit dieser Datei ziehen Sie die Website auch auf einen neuen Server um.", "Save everything (data and photos) as one zip with one click. The same file moves the site to a new server."),
        P("intro.trash", "چیزهایی که حذف کرده‌اید ۳۰ روز اینجا می‌مانند و می‌توانید برشان گردانید. بعد از ۳۰ روز خودکار پاک می‌شوند.", "Sildikleriniz 30 gün burada kalır ve geri alınabilir. Sonra otomatik silinir.", "Gelöschtes bleibt 30 Tage hier und kann wiederhergestellt werden. Danach wird es automatisch entfernt.", "Deleted items stay here for 30 days and can be restored. After that they are removed automatically."),
        P("intro.users", "کسانی که می‌توانند وارد پنل شوند. «مدیر» به همه‌چیز دسترسی دارد؛ «ویرایشگر» فقط محتوا را تغییر می‌دهد.", "Panele girebilen kişiler. \"Yönetici\" her şeye erişir; \"Editör\" sadece içeriği değiştirir.", "Wer sich anmelden darf. „Administrator“ darf alles; „Redakteur“ nur Inhalte ändern.", "People who can log in. \"Administrator\" can do everything; \"Editor\" only changes content."),

        // ---------------------------------------------------------------- where on site
        P("where.title", "این بخش کجای سایت است؟", "Bu, sitede nerede?", "Wo erscheint das?", "Where does this appear?"),
        P("where.cards", "کارت‌های خدمات در صفحه‌ی اصلی و صفحه‌ی خدمات", "Ana sayfa ve hizmetler sayfasındaki kartlar", "Karten auf Startseite und Behandlungsseite", "Service cards on the home and services pages"),
        P("where.hero", "عکس بزرگ و نوشته‌های بالای صفحه‌ی اصلی", "Ana sayfanın üstündeki büyük fotoğraf ve yazılar", "Großes Foto und Texte oben auf der Startseite", "The big photo and texts at the top of the home page"),
        P("where.about", "صفحه‌ی «درباره‌ی ما» و معرفی کوتاه صفحه‌ی اصلی", "\"Hakkımızda\" sayfası ve ana sayfadaki kısa tanıtım", "„Über uns“ und Kurzvorstellung auf der Startseite", "The About page and the short introduction on the home page"),

        // ---------------------------------------------------------------- login & account
        P("login.title", "ورود", "Giriş", "Anmelden", "Log in"),
        P("login.user", "نام کاربری", "Kullanıcı adı", "Benutzername", "Username"),
        P("login.password", "رمز عبور", "Şifre", "Passwort", "Password"),
        P("login.remember", "مرا به خاطر بسپار", "Beni hatırla", "Angemeldet bleiben", "Remember me"),
        P("login.submit", "ورود به پنل", "Giriş yap", "Anmelden", "Log in"),
        P("login.forgot", "رمز را فراموش کرده‌ام", "Şifremi unuttum", "Passwort vergessen", "Forgot password"),
        P("login.wrong", "نام کاربری یا رمز عبور درست نیست.", "Kullanıcı adı veya şifre yanlış.", "Benutzername oder Passwort ist falsch.", "Wrong username or password."),
        P("login.locked", "به خاطر چند تلاش ناموفق، ورود ۱۵ دقیقه قفل شد. بعداً دوباره امتحان کنید.", "Çok sayıda hatalı deneme nedeniyle giriş 15 dakika kilitlendi.", "Wegen zu vieler Fehlversuche ist die Anmeldung 15 Minuten gesperrt.", "Too many failed attempts – login is locked for 15 minutes."),
        P("forgot.title", "فراموشی رمز عبور", "Şifremi unuttum", "Passwort vergessen", "Forgot password"),
        P("forgot.intro", "نام کاربری یا ایمیل خود را بنویسید تا لینک تغییر رمز برایتان ایمیل شود.", "Kullanıcı adınızı veya e-postanızı yazın, şifre sıfırlama bağlantısı gönderelim.", "Benutzername oder E-Mail eingeben – wir senden einen Link zum Zurücksetzen.", "Enter your username or email and we'll email you a reset link."),
        P("forgot.send", "ارسال لینک", "Bağlantı gönder", "Link senden", "Send link"),
        P("forgot.sent", "اگر این حساب وجود داشته باشد و ایمیل داشته باشد، لینک فرستاده شد. پوشه‌ی اسپم را هم ببینید.", "Hesap varsa ve e-postası kayıtlıysa bağlantı gönderildi. Spam klasörünü de kontrol edin.", "Falls das Konto existiert und eine E-Mail hat, wurde der Link gesendet. Auch den Spam-Ordner prüfen.", "If the account exists and has an email, the link has been sent. Also check your spam folder."),
        P("forgot.noEmail", "ارسال ایمیل هنوز تنظیم نشده است. از پشتیبان فنی بخواهید رمز را با دستور «admin reset-password» عوض کند (در فایل README توضیح داده شده).", "E-posta gönderimi henüz ayarlanmadı. Teknik destekten şifreyi \"admin reset-password\" komutuyla sıfırlamasını isteyin (README'de anlatılıyor).", "Der E-Mail-Versand ist noch nicht eingerichtet. Bitten Sie den technischen Support, das Passwort mit „admin reset-password“ zurückzusetzen (siehe README).", "Email sending isn't set up yet. Ask technical support to reset the password with \"admin reset-password\" (see README)."),
        P("forgot.back", "بازگشت به صفحه‌ی ورود", "Girişe dön", "Zurück zur Anmeldung", "Back to login"),
        P("forgot.mailSubject", "تغییر رمز عبور پنل Beauty by Negin", "Beauty by Negin panel şifresi sıfırlama", "Passwort zurücksetzen – Beauty by Negin", "Reset your Beauty by Negin panel password"),
        P("forgot.mailBody", "سلام {0}،\nبرای انتخاب رمز جدید روی این لینک بزنید:\n{1}\nاگر شما درخواست نکرده‌اید، این ایمیل را نادیده بگیرید.", "Merhaba {0},\nYeni şifre belirlemek için bağlantıya tıklayın:\n{1}\nBu isteği siz yapmadıysanız bu e-postayı yok sayın.", "Hallo {0},\nüber diesen Link wählen Sie ein neues Passwort:\n{1}\nFalls Sie das nicht angefordert haben, ignorieren Sie diese E-Mail.", "Hello {0},\nuse this link to choose a new password:\n{1}\nIf you didn't request this, ignore this email."),
        P("forgot.linkInvalid", "این لینک منقضی شده یا درست نیست. دوباره درخواست بدهید.", "Bağlantının süresi dolmuş veya geçersiz. Tekrar isteyin.", "Der Link ist abgelaufen oder ungültig. Bitte neu anfordern.", "The link has expired or is invalid. Please request a new one."),
        P("account.changePassword", "تغییر رمز عبور", "Şifre değiştir", "Passwort ändern", "Change password"),
        P("account.currentPassword", "رمز فعلی", "Mevcut şifre", "Aktuelles Passwort", "Current password"),
        P("account.newPassword", "رمز جدید", "Yeni şifre", "Neues Passwort", "New password"),
        P("account.confirmPassword", "تکرار رمز جدید", "Yeni şifre (tekrar)", "Neues Passwort wiederholen", "Repeat new password"),
        P("account.passwordRules", "رمز باید حداقل ۸ حرف و حداقل یک عدد داشته باشد.", "Şifre en az 8 karakter ve en az bir rakam içermeli.", "Mindestens 8 Zeichen und mindestens eine Ziffer.", "At least 8 characters and at least one digit."),
        P("account.passwordMismatch", "دو رمز جدید یکی نیستند.", "Yeni şifreler aynı değil.", "Die neuen Passwörter stimmen nicht überein.", "The new passwords don't match."),
        P("account.currentWrong", "رمز فعلی درست نیست.", "Mevcut şifre yanlış.", "Das aktuelle Passwort ist falsch.", "The current password is wrong."),
        P("account.passwordChanged", "رمز عبور تغییر کرد.", "Şifre değiştirildi.", "Passwort geändert.", "Password changed."),
        P("account.mustChange", "برای امنیت، لطفاً قبل از ادامه یک رمز عبور جدید و شخصی انتخاب کنید.", "Güvenlik için devam etmeden önce lütfen yeni ve kişisel bir şifre belirleyin.", "Bitte wählen Sie aus Sicherheitsgründen zuerst ein neues, persönliches Passwort.", "For security, please choose a new personal password before continuing."),
        P("account.signedInAs", "وارد شده با", "Giriş yapan", "Angemeldet als", "Signed in as"),
        P("account.panelLanguage", "زبان پنل", "Panel dili", "Sprache der Verwaltung", "Panel language"),

        // ---------------------------------------------------------------- setup wizard
        P("setup.title", "راه‌اندازی اولیه", "İlk kurulum", "Ersteinrichtung", "First setup"),
        P("setup.intro", "به سایت جدیدتان خوش آمدید! این چند مورد را یک بار پر کنید؛ همه‌ی آن‌ها بعداً هم از پنل قابل تغییرند.", "Yeni sitenize hoş geldiniz! Bunları bir kez doldurun; hepsi daha sonra panelden değiştirilebilir.", "Willkommen! Füllen Sie diese Angaben einmal aus – alles lässt sich später im Panel ändern.", "Welcome to your new site! Fill these in once – everything can be changed later in the panel."),
        P("setup.account", "حساب مدیر", "Yönetici hesabı", "Administrator-Konto", "Admin account"),
        P("setup.business", "کشور و زبان", "Ülke ve dil", "Land und Sprache", "Country and language"),
        P("setup.defaultLanguageHelp", "زبانی که سایت با آن باز می‌شود.", "Sitenin açıldığı dil.", "Sprache, in der die Website startet.", "The language the site opens in."),
        P("setup.finish", "پایان و ورود به پنل", "Bitir ve panele gir", "Fertig – zur Verwaltung", "Finish and open the panel"),
        P("setup.done", "✅ راه‌اندازی انجام شد. حالا خدمات، عکس‌ها و متن‌ها را از همین پنل کامل کنید.", "✅ Kurulum tamamlandı. Şimdi hizmetleri, fotoğrafları ve metinleri tamamlayın.", "✅ Einrichtung fertig. Ergänzen Sie jetzt Behandlungen, Fotos und Texte.", "✅ Setup complete. Now complete services, photos and texts here."),

        // ---------------------------------------------------------------- appointments
        P("appt.searchHint", "نام، تلفن یا خدمت", "Ad, telefon veya hizmet", "Name, Telefon oder Behandlung", "Name, phone or service"),
        P("appt.export", "دانلود برای اکسل", "Excel için indir", "Für Excel herunterladen", "Download for Excel"),
        P("appt.empty", "هنوز درخواستی نیامده است.", "Henüz talep yok.", "Noch keine Anfragen.", "No requests yet."),
        P("appt.consultation", "مشاوره (مطمئن نیست)", "Danışmanlık (emin değil)", "Beratung (unsicher)", "Consultation (not sure)"),
        P("appt.status", "وضعیت", "Durum", "Status", "Status"),
        P("appt.call", "تماس", "Ara", "Anrufen", "Call"),
        P("appt.whatsapp", "پیام در واتس‌اپ", "WhatsApp'tan yaz", "WhatsApp", "WhatsApp"),
        P("appt.email", "ایمیل", "E-posta", "E-Mail", "Email"),
        P("appt.details", "جزئیات درخواست", "Talep ayrıntıları", "Anfrage", "Request details"),
        P("appt.phone", "تلفن", "Telefon", "Telefon", "Phone"),
        P("appt.emailAddress", "ایمیل", "E-posta", "E-Mail", "Email"),
        P("appt.service", "خدمت", "Hizmet", "Behandlung", "Service"),
        P("appt.preferred", "زمان دلخواه", "Tercih edilen zaman", "Wunschtermin", "Preferred time"),
        P("appt.received", "زمان ارسال", "Gönderilme", "Eingegangen", "Received"),
        P("appt.language", "زبان مشتری", "Müşterinin dili", "Sprache", "Language"),
        P("appt.message", "پیام مشتری", "Müşteri mesajı", "Nachricht", "Message"),
        P("appt.manage", "پیگیری", "Takip", "Bearbeitung", "Follow-up"),
        P("appt.notes", "یادداشت شما", "Notunuz", "Ihre Notiz", "Your notes"),
        P("appt.notesHelp", "فقط شما در پنل این یادداشت را می‌بینید.", "Bu notu yalnızca siz panelde görürsünüz.", "Nur Sie sehen diese Notiz im Panel.", "Only you see this note in the panel."),
        P("status.new", "جدید", "Yeni", "Neu", "New"),
        P("status.called", "تماس گرفته شد", "Arandı", "Angerufen", "Called"),
        P("status.confirmed", "تأیید شد", "Onaylandı", "Bestätigt", "Confirmed"),
        P("status.cancelled", "لغو شد", "İptal", "Abgesagt", "Cancelled"),
        P("status.completed", "انجام شد", "Tamamlandı", "Erledigt", "Completed"),

        // ---------------------------------------------------------------- messages / chats / newsletter
        P("msg.empty", "هنوز پیامی نیامده است.", "Henüz mesaj yok.", "Noch keine Nachrichten.", "No messages yet."),
        P("msg.new", "خوانده نشده", "Okunmadı", "Ungelesen", "Unread"),
        P("msg.details", "پیام", "Mesaj", "Nachricht", "Message"),
        P("chat.empty", "هنوز گفتگویی شروع نشده است.", "Henüz sohbet yok.", "Noch keine Chats.", "No chats yet."),
        P("chat.notActive", "چت در سایت نمایش داده نمی‌شود، چون ارسال ایمیل (برای کد تأیید) هنوز تنظیم نشده است.", "E-posta gönderimi (doğrulama kodu için) ayarlanmadığından sohbet sitede gösterilmiyor.", "Der Chat ist ausgeblendet, weil der E-Mail-Versand (für den Bestätigungscode) noch nicht eingerichtet ist.", "The chat is hidden because email sending (for the verification code) is not set up yet."),
        P("chat.blocked", "مسدود", "Engelli", "Blockiert", "Blocked"),
        P("chat.block", "مسدود کردن (اسپم)", "Engelle (spam)", "Blockieren (Spam)", "Block (spam)"),
        P("chat.unblock", "رفع مسدودی", "Engeli kaldır", "Freigeben", "Unblock"),
        P("chat.reply", "پاسخ شما", "Cevabınız", "Ihre Antwort", "Your reply"),
        P("chat.replyHelp", "پاسخ در پنجره‌ی چت سایت برای مشتری نمایش داده می‌شود (وقتی دوباره سایت را باز کند).", "Cevap, müşteri siteyi açtığında sohbet penceresinde görünür.", "Die Antwort erscheint im Chatfenster, sobald die Kundin die Website öffnet.", "The reply appears in the site chat window when the visitor opens the site."),
        P("chat.send", "ارسال پاسخ", "Gönder", "Senden", "Send reply"),
        P("chat.sent", "پاسخ فرستاده شد.", "Cevap gönderildi.", "Antwort gesendet.", "Reply sent."),
        P("news.count", "{0} عضو", "{0} abone", "{0} Abonnenten", "{0} subscribers"),
        P("news.empty", "هنوز کسی عضو نشده است.", "Henüz abone yok.", "Noch keine Anmeldungen.", "No subscribers yet."),

        // ---------------------------------------------------------------- services
        P("svc.count", "{0} خدمت", "{0} hizmet", "{0} Behandlungen", "{0} services"),
        P("svc.add", "افزودن خدمت", "Hizmet ekle", "Behandlung hinzufügen", "Add service"),
        P("svc.edit", "ویرایش خدمت", "Hizmeti düzenle", "Behandlung bearbeiten", "Edit service"),
        P("svc.empty", "هنوز خدمتی ثبت نشده است.", "Henüz hizmet yok.", "Noch keine Behandlungen.", "No services yet."),
        P("svc.onHome", "در صفحه‌ی اصلی", "Ana sayfada", "Auf der Startseite", "On home page"),
        P("svc.onHomeHelp", "روشن باشد تا این خدمت در بخش خدمات صفحه‌ی اصلی هم نمایش داده شود", "Açıksa hizmet ana sayfada da gösterilir", "Eingeschaltet = auch auf der Startseite zeigen", "On = also show it in the services section of the home page"),
        P("svc.texts", "متن‌ها", "Metinler", "Texte", "Texts"),
        P("svc.name", "نام خدمت", "Hizmet adı", "Name der Behandlung", "Service name"),
        P("svc.nameHelp", "مثلاً Carboxy Facial. در کارت و بالای صفحه‌ی خدمت نمایش داده می‌شود.", "Örn. Carboxy Facial. Kartta ve hizmet sayfasının üstünde görünür.", "z. B. Carboxy Facial. Erscheint auf der Karte und oben auf der Seite.", "e.g. Carboxy Facial. Shown on the card and at the top of the service page."),
        P("svc.subtitle", "زیرعنوان کوتاه", "Kısa alt başlık", "Kurzer Untertitel", "Short subtitle"),
        P("svc.subtitleHelp", "یک جمله‌ی کوتاه زیر نام، مثلاً «اکسیژن‌رسانی و شادابی پوست».", "Adın altında kısa bir cümle.", "Ein kurzer Satz unter dem Namen.", "A short line under the name."),
        P("svc.short", "توضیح کوتاه (برای کارت)", "Kısa açıklama (kart için)", "Kurztext (für die Karte)", "Short text (for the card)"),
        P("svc.shortHelp", "۱ تا ۲ جمله که روی کارت خدمت نمایش داده می‌شود.", "Hizmet kartında görünen 1-2 cümle.", "1–2 Sätze, die auf der Karte erscheinen.", "1–2 sentences shown on the service card."),
        P("svc.description", "توضیح کامل", "Ayrıntılı açıklama", "Ausführliche Beschreibung", "Full description"),
        P("svc.hwg", "یادآوری: برای آلمان از قول درمانی قطعی پرهیز کنید. به جای «درمان می‌کند» بنویسید «می‌تواند به بهبود ظاهر کمک کند».", "Hatırlatma: Almanya için kesin tıbbi vaatlerden kaçının. \"Tedavi eder\" yerine \"görünümü iyileştirmeye yardımcı olabilir\" yazın.", "Hinweis (Heilmittelwerbegesetz): keine Heilversprechen. Statt „heilt“ lieber „kann das Erscheinungsbild verbessern“.", "Reminder: avoid medical promises (German law). Instead of \"cures\" write \"can help improve the appearance\"."),
        P("svc.suitable", "مناسب برای", "Uygun olduğu ciltler", "Geeignet für", "Suitable for"),
        P("svc.suitableHelp", "مثلاً «پوست‌های کدر و خسته».", "Örn. \"Donuk ve yorgun ciltler\".", "z. B. „fahle, müde Haut“.", "e.g. \"dull, tired skin\"."),
        P("svc.result", "نتیجه‌ی مورد انتظار", "Beklenen sonuç", "Erwartetes Ergebnis", "Expected result"),
        P("svc.duration", "مدت زمان تقریبی", "Tahmini süre", "Ungefähre Dauer", "Approx. duration"),
        P("svc.durationHelp", "مثلاً «۶۰ دقیقه». اگر خالی بماند، در سایت نمایش داده نمی‌شود.", "Örn. \"60 dakika\". Boşsa sitede gösterilmez.", "z. B. „60 Min.“. Leer = wird nicht angezeigt.", "e.g. \"60 minutes\". If empty, it isn't shown."),
        P("svc.cover", "عکس اصلی", "Ana fotoğraf", "Hauptfoto", "Main photo"),
        P("svc.coverHelp", "عکس عمودی (۴:۵). بعد از انتخاب، می‌توانید قسمت دلخواه را برش بزنید.", "Dikey fotoğraf (4:5). Seçtikten sonra kırpabilirsiniz.", "Hochformat (4:5). Nach der Auswahl können Sie den Ausschnitt wählen.", "Portrait photo (4:5). After choosing you can crop it."),
        P("svc.extraImages", "عکس‌های بیشتر (اختیاری)", "Ek fotoğraflar (isteğe bağlı)", "Weitere Fotos (optional)", "More photos (optional)"),
        P("svc.extraImagesHelp", "در صفحه‌ی همین خدمت به‌صورت گالری کوچک نمایش داده می‌شوند.", "Hizmet sayfasında küçük galeri olarak gösterilir.", "Erscheinen als kleine Galerie auf der Seite der Behandlung.", "Shown as a small gallery on the service page."),
        P("svc.price", "قیمت (اختیاری)", "Fiyat (isteğe bağlı)", "Preis (optional)", "Price (optional)"),
        P("svc.priceHidden", "قیمت‌ها الان در سایت نمایش داده نمی‌شوند (از «تنظیمات کلی» قابل روشن شدن است).", "Fiyatlar şu an sitede gizli (Genel Ayarlar'dan açılabilir).", "Preise sind derzeit ausgeblendet (in den Einstellungen einschaltbar).", "Prices are currently hidden on the site (can be switched on in Settings)."),
        P("svc.priceShown", "قیمت‌ها در سایت نمایش داده می‌شوند.", "Fiyatlar sitede gösteriliyor.", "Preise werden auf der Website angezeigt.", "Prices are shown on the site."),

        // ---------------------------------------------------------------- gallery
        P("gal.add", "افزودن عکس", "Fotoğraf ekle", "Fotos hinzufügen", "Add photos"),
        P("gal.manageCategories", "مدیریت دسته‌ها", "Kategorileri yönet", "Kategorien verwalten", "Manage categories"),
        P("gal.category", "دسته", "Kategori", "Kategorie", "Category"),
        P("gal.noCategory", "بدون دسته", "Kategorisiz", "Ohne Kategorie", "No category"),
        P("gal.choosePhotos", "انتخاب عکس‌ها", "Fotoğrafları seç", "Fotos auswählen", "Choose photos"),
        P("gal.addHelp", "می‌توانید چند عکس را با هم انتخاب کنید (از گوشی یا کامپیوتر). عکس‌ها خودکار کوچک و برای سایت آماده می‌شوند.", "Birden çok fotoğraf seçebilirsiniz (telefon veya bilgisayar). Otomatik olarak küçültülür.", "Mehrere Fotos auf einmal (Handy oder Computer). Sie werden automatisch verkleinert.", "Select several photos at once (phone or computer). They are resized automatically."),
        P("gal.empty", "هنوز عکسی در این قسمت نیست.", "Burada henüz fotoğraf yok.", "Hier sind noch keine Fotos.", "No photos here yet."),
        P("gal.beforeAfter", "قبل/بعد", "Önce/Sonra", "Vorher/Nachher", "Before/After"),
        P("gal.editPhoto", "ویرایش عکس", "Fotoğrafı düzenle", "Foto bearbeiten", "Edit photo"),
        P("gal.photo", "عکس (یا عکس «قبل»)", "Fotoğraf (veya \"önce\")", "Foto (oder „Vorher“)", "Photo (or \"before\")"),
        P("gal.photoHelp", "برای عوض کردن عکس، یک عکس جدید انتخاب کنید.", "Değiştirmek için yeni bir fotoğraf seçin.", "Zum Ersetzen ein neues Foto wählen.", "Choose a new photo to replace it."),
        P("gal.afterPhoto", "عکس «بعد» (اختیاری)", "\"Sonra\" fotoğrafı (isteğe bağlı)", "„Nachher“-Foto (optional)", "\"After\" photo (optional)"),
        P("gal.afterPhotoHelp", "اگر عکس «بعد» بگذارید، در سایت یک مقایسه‌ی کشویی قبل/بعد نشان داده می‌شود. بهتر است هر دو عکس هم‌اندازه باشند.", "Bir \"sonra\" fotoğrafı eklerseniz sitede kaydırmalı karşılaştırma gösterilir. İki fotoğraf aynı boyutta olmalı.", "Mit „Nachher“-Foto erscheint ein Schieberegler-Vergleich. Beide Fotos sollten gleich groß sein.", "With an \"after\" photo the site shows a sliding comparison. Both photos should have the same size."),
        P("gal.onHome", "در صفحه‌ی اصلی", "Ana sayfada", "Auf der Startseite", "On home page"),
        P("gal.caption", "توضیح کوتاه (اختیاری)", "Kısa açıklama (isteğe bağlı)", "Kurze Beschreibung (optional)", "Short caption (optional)"),
        P("gal.captionHelp", "زیر عکس نمایش داده می‌شود و به گوگل هم کمک می‌کند.", "Fotoğrafın altında görünür ve Google'a yardımcı olur.", "Erscheint unter dem Foto und hilft Google.", "Shown under the photo and helps Google."),
        P("gal.categories", "دسته‌های گالری", "Galeri kategorileri", "Galerie-Kategorien", "Gallery categories"),
        P("gal.newCategory", "دسته‌ی جدید", "Yeni kategori", "Neue Kategorie", "New category"),

        // ---------------------------------------------------------------- reviews
        P("rev.published", "منتشرشده", "Yayında", "Veröffentlicht", "Published"),
        P("rev.pending", "منتظر تأیید", "Onay bekleyen", "Wartet auf Freigabe", "Awaiting approval"),
        P("rev.add", "افزودن نظر", "Yorum ekle", "Bewertung hinzufügen", "Add review"),
        P("rev.edit", "ویرایش نظر", "Yorumu düzenle", "Bewertung bearbeiten", "Edit review"),
        P("rev.empty", "هنوز نظری ثبت نشده است. تا وقتی نظری نباشد، بخش نظرات در سایت پنهان است.", "Henüz yorum yok. Yorum olmadığı sürece bölüm sitede gizlidir.", "Noch keine Bewertungen. Solange keine da sind, ist der Bereich ausgeblendet.", "No reviews yet. While there are none, the section is hidden on the site."),
        P("rev.addFirst", "اولین نظر را اضافه کنید", "İlk yorumu ekleyin", "Erste Bewertung hinzufügen", "Add the first review"),
        P("rev.noPending", "نظری منتظر تأیید نیست.", "Onay bekleyen yorum yok.", "Keine Bewertungen warten auf Freigabe.", "No reviews awaiting approval."),
        P("rev.visitorOff", "ثبت نظر توسط بازدیدکنندگان خاموش است (از «تنظیمات کلی» قابل روشن شدن است).", "Ziyaretçi yorumları kapalı (Genel Ayarlar'dan açılabilir).", "Bewertungen von Besuchern sind ausgeschaltet (in den Einstellungen einschaltbar).", "Visitor reviews are switched off (can be switched on in Settings)."),
        P("rev.approve", "تأیید و انتشار", "Onayla ve yayınla", "Freigeben", "Approve"),
        P("rev.approved", "نظر منتشر شد.", "Yorum yayınlandı.", "Bewertung veröffentlicht.", "Review published."),
        P("rev.pendingNote", "این نظر را یک بازدیدکننده فرستاده و هنوز در سایت نمایش داده نمی‌شود.", "Bu yorumu bir ziyaretçi gönderdi ve henüz sitede görünmüyor.", "Diese Bewertung kam von einem Besucher und ist noch nicht sichtbar.", "A visitor sent this review; it is not shown on the site yet."),
        P("rev.name", "نام مشتری", "Müşteri adı", "Name", "Client name"),
        P("rev.initials", "فقط حروف اول نام نمایش داده شود (مثلاً S. M.)", "Sadece baş harfler gösterilsin (ör. S. M.)", "Nur Initialen zeigen (z. B. S. M.)", "Show initials only (e.g. S. M.)"),
        P("rev.rating", "امتیاز", "Puan", "Sterne", "Rating"),
        P("rev.noRating", "بدون ستاره", "Yıldızsız", "Ohne Sterne", "No stars"),
        P("rev.text", "متن نظر", "Yorum metni", "Text", "Review text"),
        P("rev.textHelp", "نظر را همان‌طور که مشتری نوشته وارد کنید. نظر ساختگی ننویسید.", "Yorumu müşterinin yazdığı gibi girin. Uydurma yorum yazmayın.", "Bewertung so eintragen, wie die Kundin sie geschrieben hat. Keine erfundenen Bewertungen.", "Enter the review as the client wrote it. Never invent reviews."),
        P("rev.language", "زبان نظر", "Yorumun dili", "Sprache", "Language"),
        P("rev.languageHelp", "بازدیدکنندگان هر زبان، اول نظرهای زبان خودشان را می‌بینند.", "Ziyaretçiler önce kendi dillerindeki yorumları görür.", "Besucher sehen zuerst Bewertungen in ihrer Sprache.", "Visitors see reviews in their own language first."),
        P("rev.date", "تاریخ", "Tarih", "Datum", "Date"),
        P("rev.service", "خدمت دریافت‌شده", "Alınan hizmet", "Behandlung", "Service received"),
        P("rev.source", "منبع نظر", "Kaynak", "Quelle", "Source"),
        P("source.inperson", "حضوری", "Yüz yüze", "Persönlich", "In person"),
        P("source.instagram", "اینستاگرام", "Instagram", "Instagram", "Instagram"),
        P("source.google", "گوگل", "Google", "Google", "Google"),
        P("source.website", "سایت", "Site", "Website", "Website"),

        // ---------------------------------------------------------------- home page
        P("home.sections", "بخش‌های صفحه‌ی اصلی", "Ana sayfa bölümleri", "Bereiche der Startseite", "Home page sections"),
        P("home.sectionsHelp", "هر بخش را روشن یا خاموش کنید و با کشیدن ترتیب را عوض کنید. بخش‌های خالی (مثلاً نظرات بدون نظر) خودکار پنهان می‌شوند.", "Bölümleri açıp kapatın, sürükleyerek sıralayın. Boş bölümler (ör. yorumsuz yorumlar) otomatik gizlenir.", "Bereiche ein-/ausschalten und per Ziehen sortieren. Leere Bereiche werden automatisch ausgeblendet.", "Switch sections on/off and drag to reorder. Empty sections are hidden automatically."),
        P("home.texts", "متن‌های صفحه‌ی اصلی", "Ana sayfa metinleri", "Texte der Startseite", "Home page texts"),
        P("home.heroImage", "عکس بزرگ بالای صفحه", "Üstteki büyük fotoğraf", "Großes Foto oben", "Big photo at the top"),
        P("home.heroImageHelp", "یک عکس افقی باکیفیت (۱۶:۹) از فیشیال یا فضای کار. نوشته‌ها روی این عکس قرار می‌گیرند.", "Yüksek kaliteli yatay bir fotoğraf (16:9). Yazılar fotoğrafın üzerinde görünür.", "Hochwertiges Querformat (16:9). Die Texte liegen auf dem Foto.", "A high-quality landscape photo (16:9). The texts sit on top of it."),
        P("home.consultImage", "عکس بخش مشاوره (اختیاری)", "Danışmanlık bölümü fotoğrafı (isteğe bağlı)", "Foto im Beratungsbereich (optional)", "Consultation section photo (optional)"),
        P("home.consultImageHelp", "اگر خالی بماند، بخش مشاوره فقط متن دارد.", "Boşsa danışmanlık bölümü sadece metin içerir.", "Leer = Beratungsbereich nur mit Text.", "If empty, the consultation section shows text only."),
        P("home.aboutImageNote", "عکس بخش معرفی از عکس صفحه‌ی «درباره‌ی ما» گرفته می‌شود:", "Tanıtım bölümünün fotoğrafı \"Hakkımızda\" sayfasından alınır:", "Das Foto der Kurzvorstellung kommt von „Über uns“:", "The introduction photo comes from the About page:"),
        P("section.hero", "عکس بزرگ و شعار", "Büyük fotoğraf ve slogan", "Großes Foto & Slogan", "Big photo & slogan"),
        P("section.hero.help", "اولین چیزی که بازدیدکننده می‌بیند", "Ziyaretçinin ilk gördüğü şey", "Das Erste, was Besucher sehen", "The first thing visitors see"),
        P("section.intro", "معرفی کوتاه", "Kısa tanıtım", "Kurzvorstellung", "Short introduction"),
        P("section.intro.help", "۲-۳ جمله و لینک «درباره‌ی ما»", "2-3 cümle ve \"Hakkımızda\" bağlantısı", "2–3 Sätze und Link zu „Über uns“", "2–3 sentences and a link to About"),
        P("section.services", "خدمات منتخب", "Öne çıkan hizmetler", "Ausgewählte Behandlungen", "Featured services"),
        P("section.services.help", "خدماتی که «در صفحه‌ی اصلی» آن‌ها روشن است", "\"Ana sayfada\" açık olan hizmetler", "Behandlungen mit „Auf der Startseite“", "Services marked \"on home page\""),
        P("section.consultation", "مشاوره‌ی شخصی پوست", "Kişiye özel cilt danışmanlığı", "Persönliche Hautberatung", "Personal skin consultation"),
        P("section.consultation.help", "بخش تیره با دکمه‌های تماس", "İletişim butonlu koyu bölüm", "Dunkler Bereich mit Kontakt-Buttons", "Dark section with contact buttons"),
        P("section.gallery", "پیش‌نمایش گالری", "Galeri önizlemesi", "Galerie-Vorschau", "Gallery preview"),
        P("section.gallery.help", "چند عکس از گالری", "Galeriden birkaç fotoğraf", "Einige Fotos aus der Galerie", "A few gallery photos"),
        P("section.reviews", "نظرات", "Yorumlar", "Bewertungen", "Reviews"),
        P("section.reviews.help", "فقط وقتی نظری منتشر شده باشد نمایش داده می‌شود", "Sadece yayınlanmış yorum varsa görünür", "Nur sichtbar, wenn es Bewertungen gibt", "Only shown when there are published reviews"),
        P("section.instagram", "اینستاگرام", "Instagram", "Instagram", "Instagram"),
        P("section.instagram.help", "عکس‌هایی که در «اطلاعات تماس» آپلود می‌کنید", "\"İletişim\" bölümünde yüklediğiniz fotoğraflar", "Fotos, die Sie unter „Kontakt“ hochladen", "Photos you upload under Contact"),
        P("section.newsletter", "خبرنامه", "Bülten", "Newsletter", "Newsletter"),
        P("section.newsletter.help", "فرم عضویت ایمیل (به تلگرام هم خبر می‌دهد)", "E-posta kayıt formu (Telegram'a da bildirir)", "E-Mail-Anmeldung (meldet auch an Telegram)", "Email sign-up (also notifies Telegram)"),
        P("section.contact", "دعوت به تماس", "İletişim çağrısı", "Kontakt-Aufruf", "Contact call-to-action"),
        P("section.contact.help", "دکمه‌های تماس، واتس‌اپ، ایمیل و رزرو", "Arama, WhatsApp, e-posta ve randevu butonları", "Buttons für Anruf, WhatsApp, E-Mail, Termin", "Call, WhatsApp, email and booking buttons"),

        // ---------------------------------------------------------------- about
        P("about.texts", "متن‌های صفحه‌ی «درباره‌ی ما»", "\"Hakkımızda\" metinleri", "Texte von „Über uns“", "About page texts"),
        P("about.photo", "عکس شما", "Fotoğrafınız", "Ihr Foto", "Your photo"),
        P("about.photoHelp", "یک عکس حرفه‌ای عمودی (۴:۵). در صفحه‌ی «درباره‌ی ما» و معرفی صفحه‌ی اصلی نمایش داده می‌شود.", "Profesyonel dikey bir fotoğraf (4:5). Hakkımızda ve ana sayfa tanıtımında görünür.", "Professionelles Hochformat (4:5). Erscheint auf „Über uns“ und in der Kurzvorstellung.", "A professional portrait photo (4:5). Shown on the About page and the home introduction."),
        P("about.expertise", "زمینه‌های تخصص", "Uzmanlık alanları", "Schwerpunkte", "Areas of expertise"),
        P("about.expertiseHelp", "هر ردیف یک مورد از فهرست است. برای هر زبان در کادر خودش بنویسید.", "Her satır listedeki bir öğedir. Her dil için kendi kutusuna yazın.", "Jede Zeile ist ein Listeneintrag. Für jede Sprache ins eigene Feld schreiben.", "Each row is one list item. Write each language in its own box."),
        P("about.certificates", "مدارک و دوره‌ها", "Sertifikalar ve eğitimler", "Zertifikate & Weiterbildungen", "Certificates & training"),
        P("about.certificatesHelp", "اختیاری. اگر خالی باشد، این بخش در سایت پنهان است. کادر دوم برای توضیح است (مثلاً سال یا مؤسسه).", "İsteğe bağlı. Boşsa bölüm gizlidir. İkinci kutu açıklama içindir (ör. yıl veya kurum).", "Optional. Leer = Bereich ausgeblendet. Das zweite Feld ist für Details (z. B. Jahr oder Institut).", "Optional. If empty the section is hidden. The second box is for details (e.g. year or institute)."),
        P("about.detailPlaceholder", "توضیح (اختیاری)", "Ayrıntı (isteğe bağlı)", "Detail (optional)", "Detail (optional)"),

        // ---------------------------------------------------------------- contact
        P("contact.channels", "راه‌های تماس", "İletişim kanalları", "Kontaktwege", "Contact channels"),
        P("contact.phone", "شماره‌ی تلفن", "Telefon numarası", "Telefonnummer", "Phone number"),
        P("contact.phoneHelp", "با کد کشور، مثلاً ‎+98 912 345 6789. برای دکمه‌ی «تماس» استفاده می‌شود. با «امتحان کن» بررسی کنید.", "Ülke koduyla, ör. +90 5… \"Ara\" butonu için kullanılır. \"Dene\" ile kontrol edin.", "Mit Ländervorwahl, z. B. +49 … Für den Anruf-Button. Mit „Testen“ prüfen.", "With country code, e.g. +49 … Used by the call button. Check with \"Test\"."),
        P("contact.whatsapp", "شماره‌ی واتس‌اپ", "WhatsApp numarası", "WhatsApp-Nummer", "WhatsApp number"),
        P("contact.whatsappHelp", "با کد کشور. لینک واتس‌اپ خودکار ساخته می‌شود.", "Ülke koduyla. WhatsApp bağlantısı otomatik oluşur.", "Mit Ländervorwahl. Der WhatsApp-Link wird automatisch erstellt.", "With country code. The WhatsApp link is created automatically."),
        P("contact.email", "ایمیل", "E-posta", "E-Mail", "Email"),
        P("contact.emailHelp", "ایمیلی که مشتری‌ها در سایت می‌بینند.", "Müşterilerin sitede gördüğü e-posta.", "E-Mail-Adresse, die Kunden auf der Website sehen.", "The email visitors see on the site."),
        P("contact.instagram", "نام کاربری اینستاگرام", "Instagram kullanıcı adı", "Instagram-Name", "Instagram username"),
        P("contact.instagramHelp", "بدون @، مثلاً beautybynegin", "@ olmadan, ör. beautybynegin", "Ohne @, z. B. beautybynegin", "Without @, e.g. beautybynegin"),
        P("contact.telegram", "نام کاربری تلگرام (اختیاری)", "Telegram kullanıcı adı (isteğe bağlı)", "Telegram-Name (optional)", "Telegram username (optional)"),
        P("contact.telegramHelp", "اگر خالی بماند، دکمه‌ی تلگرام نمایش داده نمی‌شود.", "Boşsa Telegram butonu gösterilmez.", "Leer = kein Telegram-Button.", "If empty, no Telegram button is shown."),
        P("contact.mapUrl", "لینک نقشه", "Harita bağlantısı", "Karten-Link", "Map link"),
        P("contact.mapUrlHelp", "لینک موقعیت شما در نشان، بلد، Google Maps یا Apple Maps. در سایت دکمه‌ی «نمایش روی نقشه» می‌شود (نقشه‌ی گوگل داخل سایت قرار نمی‌گیرد).", "Konumunuzun harita bağlantısı. Sitede \"Haritada aç\" butonu olur (Google haritası gömülmez).", "Link zu Ihrem Standort in einer Karten-App. Wird zum Button „In Karte öffnen“ (keine eingebettete Google-Karte).", "Link to your location in a maps app. Becomes the \"Open in maps\" button (no embedded Google map)."),
        P("contact.address", "آدرس", "Adres", "Adresse", "Address"),
        P("contact.mapImage", "عکس نقشه (اختیاری)", "Harita görseli (isteğe bağlı)", "Kartenbild (optional)", "Map image (optional)"),
        P("contact.mapImageHelp", "یک اسکرین‌شات از نقشه یا عکس ورودی سالن. زیر آدرس نمایش داده می‌شود.", "Haritanın ekran görüntüsü veya girişin fotoğrafı. Adresin altında görünür.", "Screenshot der Karte oder Foto vom Eingang. Erscheint unter der Adresse.", "A map screenshot or a photo of the entrance. Shown under the address."),
        P("contact.hours", "ساعات کاری", "Çalışma saatleri", "Öffnungszeiten", "Opening hours"),
        P("contact.hoursHelp", "برای روزهای تعطیل تیک «تعطیل» را بزنید.", "Kapalı günler için \"Kapalı\"yı işaretleyin.", "Für Ruhetage „Geschlossen“ anhaken.", "Tick \"Closed\" for days off."),
        P("contact.closed", "تعطیل", "Kapalı", "Geschlossen", "Closed"),
        P("contact.opens", "از ساعت", "Açılış", "Von", "Opens"),
        P("contact.closes", "تا ساعت", "Kapanış", "Bis", "Closes"),
        P("contact.templates", "پیام‌های آماده", "Hazır mesajlar", "Vorgefertigte Nachrichten", "Ready-made messages"),
        P("contact.templatesHelp", "متن‌هایی که هنگام زدن دکمه‌ی واتس‌اپ یا ایمیل از قبل نوشته می‌شوند. {service} جای نام خدمت و {name} جای نام مشتری قرار می‌گیرد؛ این کلمه‌ها را پاک نکنید.", "WhatsApp veya e-posta butonuna basınca hazır gelen metinler. {service} hizmet adının, {name} müşteri adının yerine geçer; silmeyin.", "Texte, die beim WhatsApp- oder E-Mail-Button vorausgefüllt sind. {service} wird durch die Behandlung, {name} durch den Namen ersetzt – bitte nicht löschen.", "Texts pre-filled when the WhatsApp or email button is used. {service} becomes the service name and {name} the client's name – don't delete them."),
        P("contact.instagramBlock", "بخش اینستاگرام صفحه‌ی اصلی", "Ana sayfa Instagram bölümü", "Instagram-Bereich der Startseite", "Home page Instagram section"),
        P("contact.instagramPhotos", "عکس‌های بخش اینستاگرام", "Instagram bölümü fotoğrafları", "Fotos im Instagram-Bereich", "Instagram section photos"),
        P("contact.instagramPhotosHelp", "۶ تا ۹ عکس از پست‌هایتان آپلود کنید (اینستاگرام در ایران فیلتر است، پس عکس‌ها مستقیم روی سایت قرار می‌گیرند). زیر هر عکس می‌توانید لینک همان پست را بگذارید؛ اگر خالی بماند به صفحه‌ی اینستاگرام شما می‌رود.", "Gönderilerinizden 6-9 fotoğraf yükleyin (Instagram İran'da engelli olduğundan fotoğraflar doğrudan sitede durur). Her fotoğrafa gönderi bağlantısı ekleyebilirsiniz; boşsa profilinize gider.", "Laden Sie 6–9 Fotos Ihrer Beiträge hoch (Instagram ist im Iran gesperrt, daher liegen die Fotos auf der Website). Unter jedem Foto ist ein Beitragslink möglich; leer = Link zum Profil.", "Upload 6–9 photos of your posts (Instagram is blocked in Iran, so the photos are stored on the site). Each can link to its post; if empty it links to your profile."),
        P("contact.postLink", "لینک پست (اختیاری)", "Gönderi bağlantısı", "Beitragslink (optional)", "Post link (optional)"),

        // ---------------------------------------------------------------- pages
        P("page.add", "صفحه‌ی جدید", "Yeni sayfa", "Neue Seite", "New page"),
        P("page.edit", "ویرایش صفحه", "Sayfayı düzenle", "Seite bearbeiten", "Edit page"),
        P("page.system", "صفحه‌ی قانونی", "Yasal sayfa", "Rechtliche Seite", "Legal page"),
        P("page.inFooter", "لینک در پایین سایت", "Alt bilgide bağlantı", "Link im Fußbereich", "Link in footer"),
        P("page.inMenu", "لینک در منوی بالا", "Üst menüde bağlantı", "Link im Menü", "Link in top menu"),
        P("page.title", "عنوان صفحه", "Sayfa başlığı", "Seitentitel", "Page title"),
        P("page.content", "متن صفحه", "Sayfa metni", "Seitentext", "Page text"),
        P("page.legalNote", "این متن یک پیش‌نویس است. قبل از انتشار در آلمان، حتماً آن را به یک متخصص حقوقی نشان دهید و جاهای خالی [ ] را پر کنید.", "Bu metin bir taslaktır. Almanya'da yayınlamadan önce mutlaka bir hukuk uzmanına kontrol ettirin ve [ ] boşluklarını doldurun.", "Dieser Text ist ein Entwurf. Lassen Sie ihn vor der Veröffentlichung unbedingt von einer Fachperson prüfen und füllen Sie die [ ]-Platzhalter aus.", "This text is a draft. Have it checked by a legal expert before publishing and fill in the [ ] placeholders."),
        P("page.systemNoDelete", "صفحه‌های قانونی حذف نمی‌شوند؛ فقط می‌توانید آن‌ها را پنهان کنید.", "Yasal sayfalar silinemez; yalnızca gizlenebilir.", "Rechtliche Seiten können nicht gelöscht, nur ausgeblendet werden.", "Legal pages can't be deleted, only hidden."),

        // ---------------------------------------------------------------- site texts
        P("texts.searchHint", "مثلاً «رزرو» یا «Termin»", "ör. \"randevu\"", "z. B. „Termin“", "e.g. \"booking\""),
        P("texts.count", "{0} متن", "{0} metin", "{0} Texte", "{0} texts"),
        P("texts.missing", "{0} متن ناقص", "{0} eksik", "{0} fehlen", "{0} missing"),
        P("texts.allGroups", "همه‌ی گروه‌ها", "Tüm gruplar", "Alle Gruppen", "All groups"),
        P("texts.none", "متنی پیدا نشد.", "Metin bulunamadı.", "Keine Texte gefunden.", "No texts found."),
        P("group.nav", "منوی بالا", "Üst menü", "Menü", "Top menu"),
        P("group.buttons", "دکمه‌ها", "Butonlar", "Buttons", "Buttons"),
        P("group.bar", "نوار پایین موبایل", "Mobil alt çubuk", "Untere Leiste (Handy)", "Mobile bottom bar"),
        P("group.home", "صفحه‌ی اصلی", "Ana sayfa", "Startseite", "Home page"),
        P("group.consultation", "بخش مشاوره", "Danışmanlık bölümü", "Beratungsbereich", "Consultation block"),
        P("group.about", "درباره‌ی ما", "Hakkımızda", "Über uns", "About"),
        P("group.services", "خدمات", "Hizmetler", "Behandlungen", "Services"),
        P("group.gallery", "گالری", "Galeri", "Galerie", "Gallery"),
        P("group.reviews", "نظرات", "Yorumlar", "Bewertungen", "Reviews"),
        P("group.contact", "صفحه‌ی تماس", "İletişim sayfası", "Kontaktseite", "Contact page"),
        P("group.booking", "فرم رزرو", "Randevu formu", "Buchungsformular", "Booking form"),
        P("group.forms", "پیام‌های فرم‌ها", "Form mesajları", "Formular-Meldungen", "Form messages"),
        P("group.newsletter", "خبرنامه", "Bülten", "Newsletter", "Newsletter"),
        P("group.chat", "چت", "Sohbet", "Chat", "Chat"),
        P("group.footer", "پایین سایت", "Alt bilgi", "Fußbereich", "Footer"),
        P("group.templates", "پیام‌های آماده (واتس‌اپ/ایمیل)", "Hazır mesajlar", "Vorlagen (WhatsApp/E-Mail)", "Message templates"),
        P("group.errors", "صفحه‌های خطا و «به‌زودی»", "Hata ve \"yakında\" sayfaları", "Fehler- & „Bald“-Seiten", "Error & coming-soon pages"),
        P("group.seo", "گوگل", "Google", "Google", "Google"),

        // ---------------------------------------------------------------- languages
        P("lang.orderHelp", "ترتیب زبان‌ها در انتخاب‌گر زبان سایت (با کشیدن یا فلش‌ها). یکی را «زبان اصلی» کنید.", "Site dil seçicisindeki sıra (sürükleyin veya oklar). Birini varsayılan yapın.", "Reihenfolge im Sprachwähler (ziehen oder Pfeile). Eine Sprache als Hauptsprache wählen.", "Order in the site's language switcher (drag or arrows). Make one the main language."),
        P("lang.active", "روشن", "Açık", "Aktiv", "On"),
        P("lang.default", "زبان اصلی", "Varsayılan dil", "Hauptsprache", "Main language"),
        P("lang.nativeDigits", "اعداد فارسی/عربی (۱۲۳)", "Yerel rakamlar (۱۲۳)", "Landesziffern (۱۲۳)", "Native digits (۱۲۳)"),
        P("lang.rtl", "راست به چپ", "Sağdan sola", "Von rechts nach links", "Right to left"),
        P("lang.ltr", "چپ به راست", "Soldan sağa", "Von links nach rechts", "Left to right"),
        P("lang.disabledNote", "زبان خاموش در سایت نمایش داده نمی‌شود و آدرس‌های آن به زبان اصلی منتقل می‌شوند؛ متن‌هایش پاک نمی‌شوند.", "Kapalı bir dil sitede görünmez, adresleri ana dile yönlendirilir; metinleri silinmez.", "Ausgeschaltete Sprachen erscheinen nicht; ihre Adressen leiten auf die Hauptsprache um. Texte bleiben erhalten.", "A switched-off language is not shown and its addresses redirect to the main language; its texts are kept."),

        // ---------------------------------------------------------------- settings
        P("set.general", "عمومی", "Genel", "Allgemein", "General"),
        P("set.features", "بخش‌های سایت", "Özellikler", "Funktionen", "Features"),
        P("set.email", "ایمیل", "E-posta", "E-Mail", "Email"),
        P("set.slots", "زمان‌های فرم رزرو", "Randevu saat seçenekleri", "Zeiten im Buchungsformular", "Booking time options"),
        P("set.security", "امنیت", "Güvenlik", "Sicherheit", "Security"),
        P("set.brandName", "نام برند", "Marka adı", "Markenname", "Brand name"),
        P("set.brandNameHelp", "وقتی لوگو آپلود نشده، همین نام به‌جای لوگو نوشته می‌شود.", "Logo yoksa logo yerine bu ad yazılır.", "Ohne Logo wird dieser Name angezeigt.", "Shown instead of a logo when none is uploaded."),
        P("set.siteUrl", "آدرس اصلی سایت", "Sitenin ana adresi", "Hauptadresse der Website", "Main website address"),
        P("set.siteUrlHelp", "مثلاً https://beautybynegin.com — برای لینک‌های گوگل و تلگرام.", "ör. https://beautybynegin.com – Google ve Telegram bağlantıları için.", "z. B. https://beautybynegin.com – für Google- und Telegram-Links.", "e.g. https://beautybynegin.com – used for Google and Telegram links."),
        P("set.country", "کشور", "Ülke", "Land", "Country"),
        P("set.countryHelp", "بعد از هر جابه‌جایی (ایران → ترکیه → آلمان) این را عوض کنید.", "Her taşınmadan sonra (İran → Türkiye → Almanya) değiştirin.", "Nach jedem Umzug (Iran → Türkei → Deutschland) ändern.", "Change this after each move (Iran → Turkey → Germany)."),
        P("set.timeZone", "منطقه‌ی زمانی", "Saat dilimi", "Zeitzone", "Time zone"),
        P("set.timeZoneHelp", "برای نمایش درست ساعت درخواست‌ها و پیام‌ها.", "Taleplerin saatinin doğru gösterilmesi için.", "Damit Uhrzeiten richtig angezeigt werden.", "So times of requests and messages are shown correctly."),
        P("set.city", "شهر", "Şehir", "Stadt", "City"),
        P("set.cityHelp", "برای جستجوهای محلی در گوگل (مثلاً «فیشیال در استانبول»).", "Google'da yerel aramalar için (ör. \"İstanbul'da facial\").", "Für lokale Google-Suchen (z. B. „Facial Stuttgart“).", "For local Google searches (e.g. \"facial in Stuttgart\")."),
        P("set.addCity", "نام شهر به عنوان صفحه‌ها در گوگل اضافه شود", "Şehir adı Google başlıklarına eklensin", "Stadt an Google-Titel anhängen", "Add the city to page titles on Google"),
        P("set.logo", "لوگو (روی زمینه‌ی روشن)", "Logo (açık zemin)", "Logo (heller Hintergrund)", "Logo (light background)"),
        P("set.logoHelp", "برای بالای سایت. بهتر است PNG با زمینه‌ی شفاف باشد.", "Sitenin üstü için. Şeffaf PNG en iyisi.", "Für den Kopfbereich. Am besten PNG mit transparentem Hintergrund.", "For the header. A PNG with transparent background works best."),
        P("set.logoDark", "لوگو (روی زمینه‌ی تیره)", "Logo (koyu zemin)", "Logo (dunkler Hintergrund)", "Logo (dark background)"),
        P("set.logoDarkHelp", "نسخه‌ی روشن لوگو برای پایین سایت که زمینه‌اش تیره است (اختیاری).", "Koyu alt bilgi için açık renkli logo (isteğe bağlı).", "Helle Logo-Version für den dunklen Fußbereich (optional).", "A light version of the logo for the dark footer (optional)."),
        P("set.favicon", "آیکون کوچک مرورگر", "Tarayıcı simgesi (favicon)", "Browser-Symbol (Favicon)", "Browser icon (favicon)"),
        P("set.faviconHelp", "یک تصویر مربعی ساده؛ کنار نام سایت در تب مرورگر دیده می‌شود.", "Kare, sade bir görsel; tarayıcı sekmesinde görünür.", "Einfaches quadratisches Bild für den Browser-Tab.", "A simple square image shown in the browser tab."),
        P("set.shareImage", "عکس اشتراک‌گذاری", "Paylaşım görseli", "Vorschaubild zum Teilen", "Share image"),
        P("set.shareImageHelp", "وقتی لینک سایت در واتس‌اپ یا تلگرام فرستاده شود، این عکس نمایش داده می‌شود.", "Site bağlantısı WhatsApp veya Telegram'da paylaşılınca bu görsel görünür.", "Erscheint, wenn der Link in WhatsApp oder Telegram geteilt wird.", "Shown when the site link is shared on WhatsApp or Telegram."),
        P("set.showPrices", "نمایش قیمت‌ها در سایت", "Fiyatları sitede göster", "Preise auf der Website anzeigen", "Show prices on the site"),
        P("set.showPricesHelp", "پیش‌فرض خاموش است.", "Varsayılan: kapalı.", "Standard: aus.", "Default: off."),
        P("set.visitorReviews", "بازدیدکنندگان بتوانند نظر بنویسند", "Ziyaretçiler yorum yazabilsin", "Besucher dürfen Bewertungen schreiben", "Visitors can write reviews"),
        P("set.visitorReviewsHelp", "نظرها قبل از انتشار به «منتظر تأیید» می‌روند.", "Yorumlar yayından önce onay bekler.", "Bewertungen warten vor der Veröffentlichung auf Freigabe.", "Reviews wait for approval before being published."),
        P("set.privacyRequired", "تیک رضایت حریم خصوصی در فرم‌ها اجباری باشد", "Formlarda gizlilik onayı zorunlu olsun", "Datenschutz-Häkchen in Formularen verpflichtend", "Privacy consent tick required in forms"),
        P("set.privacyRequiredHelp", "برای آلمان و اروپا روشن بگذارید (DSGVO).", "Almanya ve AB için açık bırakın (GDPR).", "Für Deutschland/EU eingeschaltet lassen (DSGVO).", "Keep on for Germany/EU (GDPR)."),
        P("set.newsletter", "خبرنامه در صفحه‌ی اصلی", "Ana sayfada bülten", "Newsletter auf der Startseite", "Newsletter on the home page"),
        P("set.newsletterHelp", "هر عضو جدید در تلگرام هم به شما خبر داده می‌شود.", "Her yeni abone Telegram'dan da bildirilir.", "Neue Anmeldungen werden auch per Telegram gemeldet.", "Each new subscriber is also announced on Telegram."),
        P("set.chat", "دکمه‌ی چت (پایین سمت چپ)", "Sohbet butonu (sol alt)", "Chat-Button (unten links)", "Chat button (bottom left)"),
        P("set.chatHelp", "برای کار کردن، ارسال ایمیل (پایین همین صفحه) باید تنظیم شده باشد.", "Çalışması için e-posta gönderimi (aşağıda) ayarlanmış olmalı.", "Funktioniert nur mit eingerichtetem E-Mail-Versand (weiter unten).", "Needs email sending (below) to be set up."),
        P("set.maintenance", "حالت «به‌زودی» (تعمیر)", "Bakım modu (\"Yakında\")", "Wartungsmodus („Bald zurück“)", "Maintenance mode (\"Coming soon\")"),
        P("set.maintenanceHelp", "بازدیدکنندگان فقط یک صفحه‌ی زیبای «به‌زودی» با دکمه‌های تماس می‌بینند. شما که وارد پنل شده‌اید، سایت را عادی می‌بینید.", "Ziyaretçiler sadece iletişim butonlu şık bir \"yakında\" sayfası görür. Siz giriş yaptığınız için siteyi normal görürsünüz.", "Besucher sehen nur eine elegante „Bald zurück“-Seite mit Kontakt-Buttons. Angemeldet sehen Sie die Website normal.", "Visitors only see an elegant \"coming soon\" page with contact buttons. Logged in, you see the site normally."),
        P("set.autoBackup", "پشتیبان‌گیری خودکار روزانه", "Günlük otomatik yedek", "Tägliche automatische Sicherung", "Automatic daily backup"),
        P("set.autoBackupHelp", "۷ نسخه‌ی آخر نگه داشته می‌شود.", "Son 7 yedek saklanır.", "Die letzten 7 Sicherungen werden behalten.", "The last 7 backups are kept."),
        P("set.emailIntro", "برای ارسال کد تأیید چت، ایمیل اعلان درخواست‌ها و بازیابی رمز. اطلاعات SMTP را از سرویس ایمیل یا هاست خود بگیرید. توجه: سرویس‌های ایمیل خارجی از ایران همیشه کار نمی‌کنند؛ همه‌ی درخواست‌ها به‌هرحال در پنل ذخیره می‌شوند.", "Sohbet doğrulama kodu, talep bildirimleri ve şifre sıfırlama için. SMTP bilgilerini e-posta sağlayıcınızdan alın. Not: Yabancı e-posta servisleri İran'dan her zaman çalışmayabilir; tüm talepler yine de panelde saklanır.", "Für Chat-Bestätigungscodes, Benachrichtigungen und Passwort-Zurücksetzen. SMTP-Daten erhalten Sie von Ihrem E-Mail-Anbieter. Hinweis: Ausländische Dienste funktionieren aus dem Iran nicht immer; alle Anfragen werden trotzdem im Panel gespeichert.", "For chat verification codes, request notifications and password resets. Get SMTP details from your email provider. Note: foreign email services don't always work from Iran; all requests are saved in the panel anyway."),
        P("set.smtpEnabled", "ارسال ایمیل روشن باشد", "E-posta gönderimi açık", "E-Mail-Versand aktiv", "Email sending on"),
        P("set.notifyEmail", "ایمیل دریافت اعلان‌ها", "Bildirim e-postası", "E-Mail für Benachrichtigungen", "Notification email"),
        P("set.notifyEmailHelp", "درخواست‌های نوبت، پیام‌ها و چت‌های جدید به این آدرس هم فرستاده می‌شوند.", "Yeni randevu talepleri, mesajlar ve sohbetler bu adrese de gönderilir.", "Neue Anfragen, Nachrichten und Chats gehen auch an diese Adresse.", "New requests, messages and chats are also sent to this address."),
        P("set.smtpFrom", "آدرس فرستنده", "Gönderen adresi", "Absenderadresse", "Sender address"),
        P("set.smtpFromName", "نام فرستنده", "Gönderen adı", "Absendername", "Sender name"),
        P("set.smtpServer", "اطلاعات سرور ایمیل (SMTP)", "E-posta sunucusu (SMTP)", "E-Mail-Server (SMTP)", "Email server (SMTP)"),
        P("set.smtpHost", "سرور", "Sunucu", "Server", "Server"),
        P("set.smtpPort", "پورت", "Port", "Port", "Port"),
        P("set.smtpPortHelp", "معمولاً ۵۸۷ یا ۴۶۵", "Genelde 587 veya 465", "Meist 587 oder 465", "Usually 587 or 465"),
        P("set.smtpUser", "نام کاربری", "Kullanıcı adı", "Benutzername", "Username"),
        P("set.smtpPassword", "رمز", "Şifre", "Passwort", "Password"),
        P("set.smtpSsl", "اتصال امن (SSL/TLS)", "Güvenli bağlantı (SSL/TLS)", "Sichere Verbindung (SSL/TLS)", "Secure connection (SSL/TLS)"),
        P("set.secretSaved", "(ذخیره شده)", "(kayıtlı)", "(gespeichert)", "(saved)"),
        P("set.secretClear", "پاک کردن مقدار ذخیره‌شده", "Kayıtlı değeri sil", "Gespeicherten Wert löschen", "Clear the saved value"),
        P("set.secretHelp", "به‌صورت رمزنگاری‌شده ذخیره می‌شود. برای نگه داشتن مقدار قبلی، خالی بگذارید.", "Şifrelenmiş saklanır. Eskisini korumak için boş bırakın.", "Wird verschlüsselt gespeichert. Leer lassen = bisheriger Wert bleibt.", "Stored encrypted. Leave empty to keep the current value."),
        P("set.testEmail", "ارسال ایمیل آزمایشی", "Test e-postası gönder", "Test-E-Mail senden", "Send test email"),
        P("set.testAfterSave", "اول ذخیره کنید، بعد امتحان کنید.", "Önce kaydedin, sonra deneyin.", "Erst speichern, dann testen.", "Save first, then test."),
        P("set.testEmailSubject", "ایمیل آزمایشی Beauty by Negin", "Beauty by Negin test e-postası", "Test-E-Mail von Beauty by Negin", "Beauty by Negin test email"),
        P("set.testEmailBody", "اگر این ایمیل را می‌بینید، ارسال ایمیل سایت درست کار می‌کند. ✅", "Bu e-postayı görüyorsanız sitenin e-posta gönderimi çalışıyor. ✅", "Wenn Sie diese E-Mail sehen, funktioniert der E-Mail-Versand. ✅", "If you can read this, the site's email sending works. ✅"),
        P("set.testEmailOk", "ایمیل آزمایشی فرستاده شد. صندوق ایمیل (و پوشه‌ی اسپم) را ببینید.", "Test e-postası gönderildi. Gelen kutusunu (ve spam) kontrol edin.", "Test-E-Mail gesendet. Bitte Posteingang (und Spam) prüfen.", "Test email sent. Check your inbox (and spam)."),
        P("set.testEmailFail", "ارسال نشد. اطلاعات سرور، نام کاربری و رمز را بررسی کنید.", "Gönderilemedi. Sunucu, kullanıcı adı ve şifreyi kontrol edin.", "Senden fehlgeschlagen. Server, Benutzername und Passwort prüfen.", "Sending failed. Check server, username and password."),
        P("set.testEmailNoAddress", "اول «ایمیل دریافت اعلان‌ها» را بنویسید و ذخیره کنید.", "Önce bildirim e-postasını yazıp kaydedin.", "Bitte zuerst die Benachrichtigungs-E-Mail eintragen und speichern.", "Enter and save the notification email first."),
        P("set.tgIranNote", "ربات تلگرام به شما خبر می‌دهد وقتی نوبت، پیام، چت یا عضو خبرنامه‌ی جدید می‌آید. توجه: تلگرام از سرورهای داخل ایران در دسترس نیست؛ روی هاست ایرانی پیام‌ها فقط در پنل دیده می‌شوند. بعد از انتقال به ترکیه/آلمان کار می‌کند.", "Telegram botu yeni randevu, mesaj, sohbet veya bülten abonesi gelince size haber verir. Not: Telegram İran'daki sunuculardan erişilemez; İran hostunda bildirimler sadece panelde görünür.", "Der Telegram-Bot meldet neue Termine, Nachrichten, Chats und Newsletter-Anmeldungen. Hinweis: Telegram ist von iranischen Servern nicht erreichbar; dort erscheinen Meldungen nur im Panel.", "The Telegram bot tells you about new bookings, messages, chats and newsletter sign-ups. Note: Telegram is unreachable from Iranian servers; there, notifications only appear in the panel."),
        P("set.tgEnabled", "اعلان‌های تلگرام روشن باشد", "Telegram bildirimleri açık", "Telegram-Benachrichtigungen aktiv", "Telegram notifications on"),
        P("set.tgHowTo", "چطور ربات بسازم؟ (۵ قدم ساده)", "Bot nasıl oluşturulur? (5 adım)", "Wie erstelle ich den Bot? (5 Schritte)", "How do I create the bot? (5 steps)"),
        P("set.tgStep1", "در تلگرام @BotFather را جستجو و باز کنید، روی Start بزنید.", "Telegram'da @BotFather'ı açın, Start'a basın.", "In Telegram @BotFather öffnen und auf Start tippen.", "In Telegram open @BotFather and tap Start."),
        P("set.tgStep2", "بنویسید ‎/newbot و یک نام و یک نام کاربری (که با bot تمام شود) بدهید.", "/newbot yazın, bir ad ve \"bot\" ile biten kullanıcı adı verin.", "/newbot schreiben, Namen und einen Benutzernamen (endet auf „bot“) vergeben.", "Send /newbot and choose a name and a username ending in \"bot\"."),
        P("set.tgStep3", "کدی که BotFather می‌دهد (توکن) را در کادر «توکن ربات» بگذارید و ذخیره کنید.", "BotFather'ın verdiği kodu (token) \"Bot token\" kutusuna yapıştırıp kaydedin.", "Den Code (Token) von BotFather ins Feld „Bot-Token“ einfügen und speichern.", "Paste the code (token) from BotFather into \"Bot token\" and save."),
        P("set.tgStep4", "ربات خودتان را در تلگرام باز کنید و یک پیام (مثلاً «سلام») به آن بفرستید.", "Kendi botunuzu açıp bir mesaj (ör. \"merhaba\") gönderin.", "Ihren Bot öffnen und ihm eine Nachricht (z. B. „Hallo“) senden.", "Open your bot and send it a message (e.g. \"hello\")."),
        P("set.tgStep5", "روی «پیدا کردن Chat ID» بزنید، ذخیره کنید و «پیام آزمایشی» را امتحان کنید.", "\"Chat ID bul\"a basın, kaydedin ve test mesajı gönderin.", "„Chat-ID finden“ tippen, speichern und die Testnachricht senden.", "Tap \"Find Chat ID\", save, then send a test message."),
        P("set.tgToken", "توکن ربات", "Bot token", "Bot-Token", "Bot token"),
        P("set.tgFind", "پیدا کردن Chat ID", "Chat ID bul", "Chat-ID finden", "Find Chat ID"),
        P("set.tgChatHelp", "شناسه‌ی گفتگوی شما با ربات. بعد از فرستادن پیام به ربات، دکمه‌ی کنارش را بزنید.", "Botla sohbetinizin kimliği. Bota mesaj gönderdikten sonra yandaki butona basın.", "Kennung Ihres Chats mit dem Bot. Nach einer Nachricht an den Bot den Button daneben tippen.", "The ID of your chat with the bot. After messaging the bot, tap the button next to it."),
        P("set.tgWhat", "برای این موارد به تلگرام خبر بده:", "Şunlar için Telegram'a bildir:", "Per Telegram melden:", "Notify Telegram about:"),
        P("set.tgTest", "ارسال پیام آزمایشی", "Test mesajı gönder", "Testnachricht senden", "Send test message"),
        P("set.tgTestText", "پیام آزمایشی از سایت Beauty by Negin. اعلان‌های تلگرام درست کار می‌کنند.", "Beauty by Negin sitesinden test mesajı. Telegram bildirimleri çalışıyor.", "Testnachricht von Beauty by Negin. Telegram-Benachrichtigungen funktionieren.", "Test message from Beauty by Negin. Telegram notifications work."),
        P("set.tgTestOk", "پیام فرستاده شد. تلگرام را ببینید.", "Mesaj gönderildi. Telegram'ı kontrol edin.", "Nachricht gesendet. Bitte Telegram prüfen.", "Message sent. Check Telegram."),
        P("set.tgMissing", "اول توکن ربات و Chat ID را وارد و ذخیره کنید.", "Önce bot token ve Chat ID girip kaydedin.", "Bitte zuerst Bot-Token und Chat-ID eintragen und speichern.", "Enter and save the bot token and Chat ID first."),
        P("set.tgNoChats", "پیامی پیدا نشد. اول در تلگرام به ربات خودتان یک پیام بفرستید، بعد دوباره امتحان کنید.", "Mesaj bulunamadı. Önce bota bir mesaj gönderip tekrar deneyin.", "Keine Nachricht gefunden. Erst dem Bot schreiben, dann erneut versuchen.", "No message found. Send your bot a message first, then try again."),
        P("set.tgFound", "Chat ID پیدا شد و در کادر قرار گرفت. حالا ذخیره کنید.", "Chat ID bulundu ve yazıldı. Şimdi kaydedin.", "Chat-ID gefunden und eingetragen. Jetzt speichern.", "Chat ID found and filled in. Now save."),
        P("set.telegram-disabled", "اعلان تلگرام خاموش است.", "Telegram bildirimleri kapalı.", "Telegram ist ausgeschaltet.", "Telegram is switched off."),
        P("set.telegram-not-configured", "توکن یا Chat ID وارد نشده است.", "Token veya Chat ID eksik.", "Token oder Chat-ID fehlt.", "Token or Chat ID missing."),
        P("set.telegram-bad-token", "توکن ربات درست نیست. آن را دوباره از BotFather کپی کنید.", "Bot token geçersiz. BotFather'dan tekrar kopyalayın.", "Der Bot-Token ist ungültig. Bitte erneut von BotFather kopieren.", "The bot token is invalid. Copy it again from BotFather."),
        P("set.telegram-bad-chat", "Chat ID درست نیست یا هنوز به ربات پیام نداده‌اید.", "Chat ID geçersiz veya bota henüz mesaj gönderilmedi.", "Chat-ID ungültig oder dem Bot noch nicht geschrieben.", "Invalid Chat ID, or you haven't messaged the bot yet."),
        P("set.telegram-blocked-by-user", "ربات در تلگرام مسدود شده است. آن را باز کنید و Start بزنید.", "Bot engellenmiş. Botu açıp Start'a basın.", "Der Bot wurde blockiert. Bot öffnen und Start tippen.", "The bot was blocked. Open it and tap Start."),
        P("set.telegram-error", "تلگرام خطا داد. کمی بعد دوباره امتحان کنید.", "Telegram hata verdi. Biraz sonra tekrar deneyin.", "Telegram meldet einen Fehler. Später erneut versuchen.", "Telegram returned an error. Try again later."),
        P("set.telegram-unreachable", "سرور سایت به تلگرام دسترسی ندارد (در ایران عادی است). پیام‌ها همچنان در پنل ذخیره می‌شوند.", "Sunucu Telegram'a erişemiyor (İran'da normaldir). Mesajlar panelde saklanmaya devam eder.", "Der Server erreicht Telegram nicht (im Iran normal). Nachrichten werden weiterhin im Panel gespeichert.", "The server can't reach Telegram (normal in Iran). Messages are still saved in the panel."),
        P("set.slotsHelp", "گزینه‌های «زمان دلخواه» در فرم رزرو. برای هر زبان بنویسید.", "Randevu formundaki \"tercih edilen saat\" seçenekleri. Her dil için yazın.", "Auswahl „Bevorzugte Uhrzeit“ im Buchungsformular. Für jede Sprache eintragen.", "Options for \"preferred time\" in the booking form. Write them for each language."),
        P("set.https", "همیشه با https باز شود", "Her zaman https ile aç", "Immer über https öffnen", "Always use https"),
        P("set.httpsHelp", "فقط وقتی روشن کنید که گواهی SSL روی هاست نصب شده باشد؛ وگرنه سایت باز نمی‌شود.", "Yalnızca hostta SSL sertifikası kuruluysa açın; aksi halde site açılmaz.", "Nur einschalten, wenn ein SSL-Zertifikat installiert ist – sonst ist die Website nicht erreichbar.", "Only switch on when an SSL certificate is installed – otherwise the site won't open."),
        P("set.hstsHelp", "به مرورگرها می‌گوید همیشه از https استفاده کنند. فقط بعد از اطمینان از کار کردن https روشن کنید.", "Tarayıcılara hep https kullanmalarını söyler. Https'nin çalıştığından eminseniz açın.", "Weist Browser an, immer https zu nutzen. Erst einschalten, wenn https sicher funktioniert.", "Tells browsers to always use https. Only switch on once https works reliably."),
        P("country.IR", "ایران", "İran", "Iran", "Iran"),
        P("country.TR", "ترکیه", "Türkiye", "Türkei", "Türkiye"),
        P("country.DE", "آلمان", "Almanya", "Deutschland", "Germany"),
        P("country.AT", "اتریش", "Avusturya", "Österreich", "Austria"),
        P("country.CH", "سوئیس", "İsviçre", "Schweiz", "Switzerland"),
        P("country.AE", "امارات", "BAE", "VAE", "UAE"),
        P("country.GB", "بریتانیا", "Birleşik Krallık", "Vereinigtes Königreich", "United Kingdom"),

        // ---------------------------------------------------------------- backup
        P("backup.download", "گرفتن نسخه‌ی پشتیبان", "Yedek al", "Sicherung erstellen", "Create a backup"),
        P("backup.downloadHelp", "همه‌ی اطلاعات سایت (خدمات، متن‌ها، درخواست‌ها، تنظیمات) و همه‌ی عکس‌ها در یک فایل zip دانلود می‌شوند. این فایل را جای امنی نگه دارید.", "Tüm veriler (hizmetler, metinler, talepler, ayarlar) ve tüm fotoğraflar tek bir zip dosyası olarak iner. Güvenli bir yerde saklayın.", "Alle Daten (Behandlungen, Texte, Anfragen, Einstellungen) und alle Fotos werden als ZIP heruntergeladen. Sicher aufbewahren.", "All data (services, texts, requests, settings) and all photos download as one zip. Keep it somewhere safe."),
        P("backup.downloadBtn", "دانلود نسخه‌ی پشتیبان", "Yedeği indir", "Sicherung herunterladen", "Download backup"),
        P("backup.restore", "برگرداندن از نسخه‌ی پشتیبان", "Yedekten geri yükle", "Aus Sicherung wiederherstellen", "Restore from backup"),
        P("backup.restoreWarning", "با این کار همه‌ی اطلاعات و عکس‌های فعلی سایت با محتوای فایل جایگزین می‌شوند. قبل از آن، خودکار یک نسخه‌ی پشتیبان از وضعیت فعلی گرفته می‌شود. بعد از برگرداندن، با نام کاربری و رمزِ داخل همان نسخه وارد شوید.", "Bu işlem sitedeki tüm verileri ve fotoğrafları dosyanın içeriğiyle değiştirir. Öncesinde mevcut durumun otomatik yedeği alınır. Sonra o yedekteki kullanıcı adı ve şifreyle giriş yapın.", "Damit werden alle aktuellen Daten und Fotos durch den Inhalt der Datei ersetzt. Vorher wird automatisch eine Sicherung des jetzigen Stands erstellt. Danach mit Benutzername und Passwort aus dieser Sicherung anmelden.", "This replaces all current data and photos with the file's content. A backup of the current state is made automatically first. Afterwards, log in with the username and password from that backup."),
        P("backup.file", "فایل zip پشتیبان", "Yedek zip dosyası", "Sicherungsdatei (ZIP)", "Backup zip file"),
        P("backup.understand", "متوجه هستم که اطلاعات فعلی جایگزین می‌شود", "Mevcut verilerin değiştirileceğini anlıyorum", "Mir ist klar, dass die aktuellen Daten ersetzt werden", "I understand the current data will be replaced"),
        P("backup.restoreBtn", "برگرداندن", "Geri yükle", "Wiederherstellen", "Restore"),
        P("backup.restoreConfirm", "مطمئن هستید؟ همه‌ی اطلاعات فعلی با این فایل جایگزین می‌شود.", "Emin misiniz? Tüm mevcut veriler bu dosyayla değiştirilecek.", "Sind Sie sicher? Alle aktuellen Daten werden ersetzt.", "Are you sure? All current data will be replaced by this file."),
        P("backup.restored", "✅ نسخه‌ی پشتیبان برگردانده شد. لطفاً دوباره وارد شوید.", "✅ Yedek geri yüklendi. Lütfen tekrar giriş yapın.", "✅ Sicherung wiederhergestellt. Bitte erneut anmelden.", "✅ Backup restored. Please log in again."),
        P("backup.invalid", "این فایل یک نسخه‌ی پشتیبان معتبر از این سایت نیست.", "Bu dosya geçerli bir yedek değil.", "Diese Datei ist keine gültige Sicherung dieser Website.", "This file is not a valid backup of this site."),
        P("backup.chooseFile", "یک فایل انتخاب کنید و تیک تأیید را بزنید.", "Bir dosya seçin ve onay kutusunu işaretleyin.", "Datei auswählen und Bestätigung anhaken.", "Choose a file and tick the confirmation."),
        P("backup.list", "نسخه‌های ذخیره‌شده روی سرور", "Sunucudaki yedekler", "Sicherungen auf dem Server", "Backups on the server"),
        P("backup.listHelp", "نسخه‌های خودکار روزانه و نسخه‌هایی که دستی گرفته‌اید.", "Günlük otomatik ve elle alınmış yedekler.", "Tägliche automatische und manuelle Sicherungen.", "Daily automatic and manual backups."),
        P("backup.none", "هنوز نسخه‌ای ذخیره نشده است.", "Henüz yedek yok.", "Noch keine Sicherungen.", "No backups yet."),
        P("backup.auto", "خودکار", "Otomatik", "Automatisch", "Automatic"),
        P("backup.get", "دانلود", "İndir", "Herunterladen", "Download"),

        // ---------------------------------------------------------------- trash
        P("trash.empty", "سطل زباله خالی است.", "Çöp kutusu boş.", "Der Papierkorb ist leer.", "The Trash is empty."),
        P("trash.restore", "برگرداندن", "Geri al", "Wiederherstellen", "Restore"),
        P("trash.restored", "برگردانده شد.", "Geri alındı.", "Wiederhergestellt.", "Restored."),
        P("trash.deleteForever", "حذف برای همیشه", "Kalıcı olarak sil", "Endgültig löschen", "Delete forever"),
        P("trash.confirmForever", "این مورد برای همیشه پاک می‌شود و دیگر قابل برگشت نیست. ادامه می‌دهید؟", "Bu öğe kalıcı olarak silinecek ve geri alınamayacak. Devam edilsin mi?", "Wird endgültig gelöscht und kann nicht wiederhergestellt werden. Fortfahren?", "This will be deleted forever and can't be restored. Continue?"),
        P("trash.daysLeft", "{0} روز تا پاک شدن خودکار", "Otomatik silinmeye {0} gün", "Noch {0} Tage bis zur automatischen Löschung", "{0} days until automatic removal"),
        P("kind.service", "خدمت", "Hizmet", "Behandlung", "Service"),
        P("kind.gallery-item", "عکس گالری", "Galeri fotoğrafı", "Galeriefoto", "Gallery photo"),
        P("kind.gallery-category", "دسته‌ی گالری", "Galeri kategorisi", "Galerie-Kategorie", "Gallery category"),
        P("kind.review", "نظر", "Yorum", "Bewertung", "Review"),
        P("kind.page", "صفحه", "Sayfa", "Seite", "Page"),
        P("kind.appointment", "درخواست نوبت", "Randevu talebi", "Terminanfrage", "Appointment request"),
        P("kind.message", "پیام", "Mesaj", "Nachricht", "Message"),
        P("kind.chat", "گفتگو", "Sohbet", "Chat", "Chat"),
        P("kind.subscriber", "عضو خبرنامه", "Bülten abonesi", "Newsletter-Abonnent", "Subscriber"),
        P("kind.list-item", "مورد فهرست", "Liste öğesi", "Listeneintrag", "List item"),
        P("kind.instagram", "عکس اینستاگرام", "Instagram fotoğrafı", "Instagram-Foto", "Instagram photo"),
        P("kind.time-slot", "زمان فرم رزرو", "Randevu saati", "Buchungszeit", "Booking time"),

        // ---------------------------------------------------------------- users
        P("users.add", "افزودن کاربر", "Kullanıcı ekle", "Benutzer hinzufügen", "Add user"),
        P("users.admin", "مدیر", "Yönetici", "Administrator", "Administrator"),
        P("users.editor", "ویرایشگر", "Editör", "Redakteur", "Editor"),
        P("users.role", "نقش", "Rol", "Rolle", "Role"),
        P("users.roleHelp", "ویرایشگر فقط محتوا (خدمات، عکس‌ها، متن‌ها، درخواست‌ها) را تغییر می‌دهد؛ به تنظیمات، پشتیبان‌گیری و کاربران دسترسی ندارد.", "Editör sadece içeriği değiştirir; ayarlar, yedekleme ve kullanıcılara erişemez.", "Redakteure ändern nur Inhalte; kein Zugriff auf Einstellungen, Sicherung und Benutzer.", "Editors only change content; no access to settings, backup or users."),
        P("users.displayName", "نام نمایشی", "Görünen ad", "Anzeigename", "Display name"),
        P("users.emailHelp", "برای «فراموشی رمز» لازم است (اختیاری).", "\"Şifremi unuttum\" için gerekir (isteğe bağlı).", "Für „Passwort vergessen“ nötig (optional).", "Needed for \"forgot password\" (optional)."),
        P("users.tempPassword", "رمز موقت", "Geçici şifre", "Vorläufiges Passwort", "Temporary password"),
        P("users.resetPassword", "تعیین رمز جدید", "Yeni şifre belirle", "Neues Passwort setzen", "Set new password"),
        P("users.locked", "قفل شده", "Kilitli", "Gesperrt", "Locked"),
        P("users.created", "کاربر ساخته شد. باید در اولین ورود رمزش را عوض کند.", "Kullanıcı oluşturuldu. İlk girişte şifresini değiştirmesi gerekecek.", "Benutzer angelegt. Beim ersten Anmelden muss das Passwort geändert werden.", "User created. They must change the password at first login."),
        P("users.createFailed", "کاربر ساخته نشد. شاید این نام کاربری قبلاً استفاده شده است.", "Kullanıcı oluşturulamadı. Bu ad zaten kullanılıyor olabilir.", "Benutzer konnte nicht angelegt werden. Der Name ist evtl. schon vergeben.", "Couldn't create the user. The username may already exist."),
        P("users.passwordReset", "رمز جدید تنظیم و حساب باز شد.", "Yeni şifre ayarlandı ve hesap açıldı.", "Neues Passwort gesetzt und Konto entsperrt.", "New password set and account unlocked."),
        P("users.cannotDeleteSelf", "نمی‌توانید حساب خودتان را حذف کنید.", "Kendi hesabınızı silemezsiniz.", "Sie können Ihr eigenes Konto nicht löschen.", "You can't delete your own account."),
        P("users.lastAdmin", "حداقل یک مدیر باید باقی بماند.", "En az bir yönetici kalmalı.", "Mindestens ein Administrator muss bleiben.", "At least one administrator must remain."),

        // ---------------------------------------------------------------- help
        P("help.missing", "فایل راهنما پیدا نشد (docs/panel-rehberi-fa.md).", "Kılavuz dosyası bulunamadı.", "Die Anleitung wurde nicht gefunden.", "The guide file was not found."),
    ];
}
